/*
 * Copyright (c) 2024 iterate GmbH. All rights reserved.
 */

package ch.iterate.hub.crypto;

import ch.cyberduck.core.cryptomator.random.FastSecureRandomProvider;

import org.cryptomator.cryptolib.common.P384KeyPair;
import org.junit.jupiter.api.Test;

import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.text.ParseException;
import java.util.Base64;
import java.util.Collections;
import java.util.Map;

import ch.iterate.hub.crypto.exceptions.NotECKeyException;
import ch.iterate.hub.model.JWEPayload;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.nimbusds.jose.JOSEException;
import com.nimbusds.jose.Payload;

import static org.junit.jupiter.api.Assertions.assertEquals;

class JWETest {
    @Test
    public void testEcdhEsEncryptDecrypt() throws ParseException, JOSEException, NoSuchAlgorithmException, InvalidKeySpecException, NotECKeyException, JsonProcessingException {
        final P384KeyPair keyPair = P384KeyPair.generate();
        final Map<String, Object> orig = Collections.singletonMap("hello", "world");
        final String jwe = JWE.ecdhEsEncrypt(new JWEPayload() {
            @Override
            public Map<String, Object> toJSONObject() {
                return orig;
            }
        }, "newkids", keyPair.getPublic());
        final Payload decrypted = JWE.decryptEcdhEs(jwe, keyPair.getPrivate());
        assertEquals(Collections.singletonMap("hello", "world"), decrypted.toJSONObject());
    }

    @Test
    public void testPbes2EncryptDecrypt() throws JOSEException, ParseException, JsonProcessingException {
        final String setupCode = "topsecret";
        final JWEPayload payload = new JWEPayload() {
            @Override
            public Map<String, Object> toJSONObject() {
                return Collections.singletonMap("hello", "world");
            }
        };
        final String jwe = JWE.pbes2Encrypt(payload, "kiddo", setupCode);
        final Payload decryptedPayload = JWE.decryptPbes2(jwe, setupCode);
        assertEquals(1, decryptedPayload.toJSONObject().size());
        assertEquals("world", decryptedPayload.toJSONObject().get("hello"));
    }

    @Test
    public void testA256EncryptDecrypt() throws JOSEException, JsonProcessingException, ParseException {
        final byte[] kek = new byte[32];
        FastSecureRandomProvider.get().provide().nextBytes(kek);
        final String jwe = JWE.a256kwEncrypt(new JWEPayload() {
            @Override
            public Map<String, Object> toJSONObject() {
                return Collections.singletonMap("hello", "world");
            }
        }, "kiddy", kek);
        assertEquals(Collections.singletonMap("hello", "world"), JWE.decryptA256kw(jwe, kek).toJSONObject());
    }

    @Test
    public void testDecryptPbes2() throws ParseException, JOSEException {
        final Payload payload = JWE.decryptPbes2("eyJhbGciOiJQQkVTMi1IUzUxMitBMjU2S1ciLCJlbmMiOiJBMjU2R0NNIiwicDJzIjoiQmp4NXBKU0lrSU5EZHJOS0pjTmdiUSIsInAyYyI6MTAwMDAwMCwiYXB1IjoiIiwiYXB2IjoiIn0.-sXeL9JD6MMhGEkdtP9LmIXGCHnVI5d7ifjO5WnWoz7d8Qsl7RmiQA.lmo9F4fSsukqfvuc.3o1l8RVc62czjv-fdi-jQJnijapO.n2ou6Oi04QOeGtiqrQhFRw", "topsecret");
        assertEquals(payload.toJSONObject().get("key"), "hello world");
    }

    @Test
    public void testDecryptA256kw() throws ParseException, JOSEException {
        // JWE generated by https://dinochiesa.github.io/jwt/
        final String jwe = "eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMjU2R0NNIn0.JTSrGbw4XEKXYFTC7siTT7DIZUX2SogThcLKXgxe0FPK3Fi8ckjr9A.zQx0t4qoTVIc-h5f.cmqzZ-md3cvdTNH9FWbKOsw.DCdGhmdwjoYKIuNC5zgQJQ";
        final byte[] rawKek = Base64.getUrlDecoder().decode("y_uxz8iAtcOXlqMYpm2jASvDWokpCYMtwkthFSK6IF0");
        assertEquals(32, rawKek.length);
        final Payload decrypted = JWE.decryptA256kw(jwe, rawKek);
        assertEquals(Collections.singletonMap("hello", "world"), decrypted.toJSONObject());
    }
}