/*
 * hub-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.iterate.hub.client.model;

import org.joda.time.DateTime;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;


/**
 * ConfigDto
 */
@JsonPropertyOrder({
        ConfigDto.JSON_PROPERTY_KEYCLOAK_URL,
        ConfigDto.JSON_PROPERTY_KEYCLOAK_REALM,
        ConfigDto.JSON_PROPERTY_KEYCLOAK_CLIENT_ID_HUB,
        ConfigDto.JSON_PROPERTY_KEYCLOAK_CLIENT_ID_CRYPTOMATOR,
        ConfigDto.JSON_PROPERTY_KEYCLOAK_AUTH_ENDPOINT,
        ConfigDto.JSON_PROPERTY_KEYCLOAK_TOKEN_ENDPOINT,
        ConfigDto.JSON_PROPERTY_SERVER_TIME,
        ConfigDto.JSON_PROPERTY_API_LEVEL,
        ConfigDto.JSON_PROPERTY_KEYCLOAK_CLIENT_ID_CRYPTOMATOR_VAULTS,
        ConfigDto.JSON_PROPERTY_UUID
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ConfigDto {
    public static final String JSON_PROPERTY_KEYCLOAK_URL = "keycloakUrl";
    private String keycloakUrl;

    public static final String JSON_PROPERTY_KEYCLOAK_REALM = "keycloakRealm";
    private String keycloakRealm;

    public static final String JSON_PROPERTY_KEYCLOAK_CLIENT_ID_HUB = "keycloakClientIdHub";
    private String keycloakClientIdHub;

    public static final String JSON_PROPERTY_KEYCLOAK_CLIENT_ID_CRYPTOMATOR = "keycloakClientIdCryptomator";
    private String keycloakClientIdCryptomator;

    public static final String JSON_PROPERTY_KEYCLOAK_AUTH_ENDPOINT = "keycloakAuthEndpoint";
    private String keycloakAuthEndpoint;

    public static final String JSON_PROPERTY_KEYCLOAK_TOKEN_ENDPOINT = "keycloakTokenEndpoint";
    private String keycloakTokenEndpoint;

    public static final String JSON_PROPERTY_SERVER_TIME = "serverTime";
    private DateTime serverTime;

    public static final String JSON_PROPERTY_API_LEVEL = "apiLevel";
    private Integer apiLevel;

    public static final String JSON_PROPERTY_KEYCLOAK_CLIENT_ID_CRYPTOMATOR_VAULTS = "keycloakClientIdCryptomatorVaults";
    private String keycloakClientIdCryptomatorVaults;

    public static final String JSON_PROPERTY_UUID = "uuid";
    private String uuid;

    public ConfigDto() {
    }

    public ConfigDto keycloakUrl(String keycloakUrl) {
        this.keycloakUrl = keycloakUrl;
        return this;
    }

    /**
     * Get keycloakUrl
     *
     * @return keycloakUrl
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_KEYCLOAK_URL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getKeycloakUrl() {
        return keycloakUrl;
    }


    @JsonProperty(JSON_PROPERTY_KEYCLOAK_URL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setKeycloakUrl(String keycloakUrl) {
        this.keycloakUrl = keycloakUrl;
    }


    public ConfigDto keycloakRealm(String keycloakRealm) {
        this.keycloakRealm = keycloakRealm;
        return this;
    }

    /**
     * Get keycloakRealm
     *
     * @return keycloakRealm
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_KEYCLOAK_REALM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getKeycloakRealm() {
        return keycloakRealm;
    }


    @JsonProperty(JSON_PROPERTY_KEYCLOAK_REALM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setKeycloakRealm(String keycloakRealm) {
        this.keycloakRealm = keycloakRealm;
    }


    public ConfigDto keycloakClientIdHub(String keycloakClientIdHub) {
        this.keycloakClientIdHub = keycloakClientIdHub;
        return this;
    }

    /**
     * Get keycloakClientIdHub
     *
     * @return keycloakClientIdHub
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_KEYCLOAK_CLIENT_ID_HUB)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getKeycloakClientIdHub() {
        return keycloakClientIdHub;
    }


    @JsonProperty(JSON_PROPERTY_KEYCLOAK_CLIENT_ID_HUB)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setKeycloakClientIdHub(String keycloakClientIdHub) {
        this.keycloakClientIdHub = keycloakClientIdHub;
    }


    public ConfigDto keycloakClientIdCryptomator(String keycloakClientIdCryptomator) {
        this.keycloakClientIdCryptomator = keycloakClientIdCryptomator;
        return this;
    }

    /**
     * Get keycloakClientIdCryptomator
     *
     * @return keycloakClientIdCryptomator
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_KEYCLOAK_CLIENT_ID_CRYPTOMATOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getKeycloakClientIdCryptomator() {
        return keycloakClientIdCryptomator;
    }


    @JsonProperty(JSON_PROPERTY_KEYCLOAK_CLIENT_ID_CRYPTOMATOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setKeycloakClientIdCryptomator(String keycloakClientIdCryptomator) {
        this.keycloakClientIdCryptomator = keycloakClientIdCryptomator;
    }


    public ConfigDto keycloakAuthEndpoint(String keycloakAuthEndpoint) {
        this.keycloakAuthEndpoint = keycloakAuthEndpoint;
        return this;
    }

    /**
     * Get keycloakAuthEndpoint
     *
     * @return keycloakAuthEndpoint
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_KEYCLOAK_AUTH_ENDPOINT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getKeycloakAuthEndpoint() {
        return keycloakAuthEndpoint;
    }


    @JsonProperty(JSON_PROPERTY_KEYCLOAK_AUTH_ENDPOINT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setKeycloakAuthEndpoint(String keycloakAuthEndpoint) {
        this.keycloakAuthEndpoint = keycloakAuthEndpoint;
    }


    public ConfigDto keycloakTokenEndpoint(String keycloakTokenEndpoint) {
        this.keycloakTokenEndpoint = keycloakTokenEndpoint;
        return this;
    }

    /**
     * Get keycloakTokenEndpoint
     *
     * @return keycloakTokenEndpoint
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_KEYCLOAK_TOKEN_ENDPOINT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getKeycloakTokenEndpoint() {
        return keycloakTokenEndpoint;
    }


    @JsonProperty(JSON_PROPERTY_KEYCLOAK_TOKEN_ENDPOINT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setKeycloakTokenEndpoint(String keycloakTokenEndpoint) {
        this.keycloakTokenEndpoint = keycloakTokenEndpoint;
    }


    public ConfigDto serverTime(DateTime serverTime) {
        this.serverTime = serverTime;
        return this;
    }

    /**
     * Get serverTime
     *
     * @return serverTime
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(example = "2022-03-10T16:15:50Z", value = "")
    @JsonProperty(JSON_PROPERTY_SERVER_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public DateTime getServerTime() {
        return serverTime;
    }


    @JsonProperty(JSON_PROPERTY_SERVER_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setServerTime(DateTime serverTime) {
        this.serverTime = serverTime;
    }


    public ConfigDto apiLevel(Integer apiLevel) {
        this.apiLevel = apiLevel;
        return this;
    }

    /**
     * Get apiLevel
     *
     * @return apiLevel
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_API_LEVEL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getApiLevel() {
        return apiLevel;
    }


    @JsonProperty(JSON_PROPERTY_API_LEVEL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setApiLevel(Integer apiLevel) {
        this.apiLevel = apiLevel;
    }


    public ConfigDto keycloakClientIdCryptomatorVaults(String keycloakClientIdCryptomatorVaults) {
        this.keycloakClientIdCryptomatorVaults = keycloakClientIdCryptomatorVaults;
        return this;
    }

    /**
     * Get keycloakClientIdCryptomatorVaults
     *
     * @return keycloakClientIdCryptomatorVaults
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_KEYCLOAK_CLIENT_ID_CRYPTOMATOR_VAULTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getKeycloakClientIdCryptomatorVaults() {
        return keycloakClientIdCryptomatorVaults;
    }


    @JsonProperty(JSON_PROPERTY_KEYCLOAK_CLIENT_ID_CRYPTOMATOR_VAULTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setKeycloakClientIdCryptomatorVaults(String keycloakClientIdCryptomatorVaults) {
        this.keycloakClientIdCryptomatorVaults = keycloakClientIdCryptomatorVaults;
    }


    public ConfigDto uuid(String uuid) {
        this.uuid = uuid;
        return this;
    }

    /**
     * Get uuid
     *
     * @return uuid
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_UUID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getUuid() {
        return uuid;
    }


    @JsonProperty(JSON_PROPERTY_UUID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }


    /**
     * Return true if this ConfigDto object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if(this == o) {
            return true;
        }
        if(o == null || getClass() != o.getClass()) {
            return false;
        }
        ConfigDto configDto = (ConfigDto) o;
        return Objects.equals(this.keycloakUrl, configDto.keycloakUrl) &&
                Objects.equals(this.keycloakRealm, configDto.keycloakRealm) &&
                Objects.equals(this.keycloakClientIdHub, configDto.keycloakClientIdHub) &&
                Objects.equals(this.keycloakClientIdCryptomator, configDto.keycloakClientIdCryptomator) &&
                Objects.equals(this.keycloakAuthEndpoint, configDto.keycloakAuthEndpoint) &&
                Objects.equals(this.keycloakTokenEndpoint, configDto.keycloakTokenEndpoint) &&
                Objects.equals(this.serverTime, configDto.serverTime) &&
                Objects.equals(this.apiLevel, configDto.apiLevel) &&
                Objects.equals(this.keycloakClientIdCryptomatorVaults, configDto.keycloakClientIdCryptomatorVaults) &&
                Objects.equals(this.uuid, configDto.uuid);
    }

    @Override
    public int hashCode() {
        return Objects.hash(keycloakUrl, keycloakRealm, keycloakClientIdHub, keycloakClientIdCryptomator, keycloakAuthEndpoint, keycloakTokenEndpoint, serverTime, apiLevel, keycloakClientIdCryptomatorVaults, uuid);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ConfigDto {\n");
        sb.append("    keycloakUrl: ").append(toIndentedString(keycloakUrl)).append("\n");
        sb.append("    keycloakRealm: ").append(toIndentedString(keycloakRealm)).append("\n");
        sb.append("    keycloakClientIdHub: ").append(toIndentedString(keycloakClientIdHub)).append("\n");
        sb.append("    keycloakClientIdCryptomator: ").append(toIndentedString(keycloakClientIdCryptomator)).append("\n");
        sb.append("    keycloakAuthEndpoint: ").append(toIndentedString(keycloakAuthEndpoint)).append("\n");
        sb.append("    keycloakTokenEndpoint: ").append(toIndentedString(keycloakTokenEndpoint)).append("\n");
        sb.append("    serverTime: ").append(toIndentedString(serverTime)).append("\n");
        sb.append("    apiLevel: ").append(toIndentedString(apiLevel)).append("\n");
        sb.append("    keycloakClientIdCryptomatorVaults: ").append(toIndentedString(keycloakClientIdCryptomatorVaults)).append("\n");
        sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

