/*
 * hub-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.iterate.hub.client.model;

import java.util.Objects;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;


/**
 * CreateS3STSBucketDto
 */
@JsonPropertyOrder({
        CreateS3STSBucketDto.JSON_PROPERTY_VAULT_ID,
        CreateS3STSBucketDto.JSON_PROPERTY_STORAGE_CONFIG_ID,
        CreateS3STSBucketDto.JSON_PROPERTY_VAULT_UVF,
        CreateS3STSBucketDto.JSON_PROPERTY_ROOT_DIR_HASH,
        CreateS3STSBucketDto.JSON_PROPERTY_AWS_ACCESS_KEY,
        CreateS3STSBucketDto.JSON_PROPERTY_AWS_SECRET_KEY,
        CreateS3STSBucketDto.JSON_PROPERTY_SESSION_TOKEN,
        CreateS3STSBucketDto.JSON_PROPERTY_REGION
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CreateS3STSBucketDto {
    public static final String JSON_PROPERTY_VAULT_ID = "vaultId";
    private String vaultId;

    public static final String JSON_PROPERTY_STORAGE_CONFIG_ID = "storageConfigId";
    private UUID storageConfigId;

    public static final String JSON_PROPERTY_VAULT_UVF = "vaultUvf";
    private String vaultUvf;

    public static final String JSON_PROPERTY_ROOT_DIR_HASH = "rootDirHash";
    private String rootDirHash;

    public static final String JSON_PROPERTY_AWS_ACCESS_KEY = "awsAccessKey";
    private String awsAccessKey;

    public static final String JSON_PROPERTY_AWS_SECRET_KEY = "awsSecretKey";
    private String awsSecretKey;

    public static final String JSON_PROPERTY_SESSION_TOKEN = "sessionToken";
    private String sessionToken;

    public static final String JSON_PROPERTY_REGION = "region";
    private String region;

    public CreateS3STSBucketDto() {
    }

    public CreateS3STSBucketDto vaultId(String vaultId) {
        this.vaultId = vaultId;
        return this;
    }

    /**
     * Get vaultId
     *
     * @return vaultId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_VAULT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getVaultId() {
        return vaultId;
    }


    @JsonProperty(JSON_PROPERTY_VAULT_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVaultId(String vaultId) {
        this.vaultId = vaultId;
    }


    public CreateS3STSBucketDto storageConfigId(UUID storageConfigId) {
        this.storageConfigId = storageConfigId;
        return this;
    }

    /**
     * Get storageConfigId
     *
     * @return storageConfigId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_STORAGE_CONFIG_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public UUID getStorageConfigId() {
        return storageConfigId;
    }


    @JsonProperty(JSON_PROPERTY_STORAGE_CONFIG_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStorageConfigId(UUID storageConfigId) {
        this.storageConfigId = storageConfigId;
    }


    public CreateS3STSBucketDto vaultUvf(String vaultUvf) {
        this.vaultUvf = vaultUvf;
        return this;
    }

    /**
     * Get vaultUvf
     *
     * @return vaultUvf
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_VAULT_UVF)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getVaultUvf() {
        return vaultUvf;
    }


    @JsonProperty(JSON_PROPERTY_VAULT_UVF)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVaultUvf(String vaultUvf) {
        this.vaultUvf = vaultUvf;
    }


    public CreateS3STSBucketDto rootDirHash(String rootDirHash) {
        this.rootDirHash = rootDirHash;
        return this;
    }

    /**
     * Get rootDirHash
     *
     * @return rootDirHash
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_ROOT_DIR_HASH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getRootDirHash() {
        return rootDirHash;
    }


    @JsonProperty(JSON_PROPERTY_ROOT_DIR_HASH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRootDirHash(String rootDirHash) {
        this.rootDirHash = rootDirHash;
    }


    public CreateS3STSBucketDto awsAccessKey(String awsAccessKey) {
        this.awsAccessKey = awsAccessKey;
        return this;
    }

    /**
     * Get awsAccessKey
     *
     * @return awsAccessKey
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_AWS_ACCESS_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getAwsAccessKey() {
        return awsAccessKey;
    }


    @JsonProperty(JSON_PROPERTY_AWS_ACCESS_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAwsAccessKey(String awsAccessKey) {
        this.awsAccessKey = awsAccessKey;
    }


    public CreateS3STSBucketDto awsSecretKey(String awsSecretKey) {
        this.awsSecretKey = awsSecretKey;
        return this;
    }

    /**
     * Get awsSecretKey
     *
     * @return awsSecretKey
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_AWS_SECRET_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getAwsSecretKey() {
        return awsSecretKey;
    }


    @JsonProperty(JSON_PROPERTY_AWS_SECRET_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAwsSecretKey(String awsSecretKey) {
        this.awsSecretKey = awsSecretKey;
    }


    public CreateS3STSBucketDto sessionToken(String sessionToken) {
        this.sessionToken = sessionToken;
        return this;
    }

    /**
     * Get sessionToken
     *
     * @return sessionToken
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_SESSION_TOKEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getSessionToken() {
        return sessionToken;
    }


    @JsonProperty(JSON_PROPERTY_SESSION_TOKEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSessionToken(String sessionToken) {
        this.sessionToken = sessionToken;
    }


    public CreateS3STSBucketDto region(String region) {
        this.region = region;
        return this;
    }

    /**
     * Get region
     *
     * @return region
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_REGION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getRegion() {
        return region;
    }


    @JsonProperty(JSON_PROPERTY_REGION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRegion(String region) {
        this.region = region;
    }


    /**
     * Return true if this CreateS3STSBucketDto object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if(this == o) {
            return true;
        }
        if(o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateS3STSBucketDto createS3STSBucketDto = (CreateS3STSBucketDto) o;
        return Objects.equals(this.vaultId, createS3STSBucketDto.vaultId) &&
                Objects.equals(this.storageConfigId, createS3STSBucketDto.storageConfigId) &&
                Objects.equals(this.vaultUvf, createS3STSBucketDto.vaultUvf) &&
                Objects.equals(this.rootDirHash, createS3STSBucketDto.rootDirHash) &&
                Objects.equals(this.awsAccessKey, createS3STSBucketDto.awsAccessKey) &&
                Objects.equals(this.awsSecretKey, createS3STSBucketDto.awsSecretKey) &&
                Objects.equals(this.sessionToken, createS3STSBucketDto.sessionToken) &&
                Objects.equals(this.region, createS3STSBucketDto.region);
    }

    @Override
    public int hashCode() {
        return Objects.hash(vaultId, storageConfigId, vaultUvf, rootDirHash, awsAccessKey, awsSecretKey, sessionToken, region);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreateS3STSBucketDto {\n");
        sb.append("    vaultId: ").append(toIndentedString(vaultId)).append("\n");
        sb.append("    storageConfigId: ").append(toIndentedString(storageConfigId)).append("\n");
        sb.append("    vaultUvf: ").append(toIndentedString(vaultUvf)).append("\n");
        sb.append("    rootDirHash: ").append(toIndentedString(rootDirHash)).append("\n");
        sb.append("    awsAccessKey: ").append(toIndentedString(awsAccessKey)).append("\n");
        sb.append("    awsSecretKey: ").append(toIndentedString(awsSecretKey)).append("\n");
        sb.append("    sessionToken: ").append(toIndentedString(sessionToken)).append("\n");
        sb.append("    region: ").append(toIndentedString(region)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

