/*
 * hub-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.iterate.hub.client.model;

import org.joda.time.DateTime;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;


/**
 * DeviceDto
 */
@JsonPropertyOrder({
        DeviceDto.JSON_PROPERTY_ID,
        DeviceDto.JSON_PROPERTY_NAME,
        DeviceDto.JSON_PROPERTY_TYPE,
        DeviceDto.JSON_PROPERTY_PUBLIC_KEY,
        DeviceDto.JSON_PROPERTY_USER_PRIVATE_KEY,
        DeviceDto.JSON_PROPERTY_OWNER,
        DeviceDto.JSON_PROPERTY_CREATION_TIME
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DeviceDto {
    public static final String JSON_PROPERTY_ID = "id";
    private String id;

    public static final String JSON_PROPERTY_NAME = "name";
    private String name;

    public static final String JSON_PROPERTY_TYPE = "type";
    private Type1 type;

    public static final String JSON_PROPERTY_PUBLIC_KEY = "publicKey";
    private String publicKey;

    public static final String JSON_PROPERTY_USER_PRIVATE_KEY = "userPrivateKey";
    private String userPrivateKey;

    public static final String JSON_PROPERTY_OWNER = "owner";
    private String owner;

    public static final String JSON_PROPERTY_CREATION_TIME = "creationTime";
    private DateTime creationTime;

    public DeviceDto() {
    }

    public DeviceDto id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getId() {
        return id;
    }


    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setId(String id) {
        this.id = id;
    }


    public DeviceDto name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getName() {
        return name;
    }


    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setName(String name) {
        this.name = name;
    }


    public DeviceDto type(Type1 type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Type1 getType() {
        return type;
    }


    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setType(Type1 type) {
        this.type = type;
    }


    public DeviceDto publicKey(String publicKey) {
        this.publicKey = publicKey;
        return this;
    }

    /**
     * Get publicKey
     *
     * @return publicKey
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    @JsonProperty(JSON_PROPERTY_PUBLIC_KEY)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getPublicKey() {
        return publicKey;
    }


    @JsonProperty(JSON_PROPERTY_PUBLIC_KEY)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setPublicKey(String publicKey) {
        this.publicKey = publicKey;
    }


    public DeviceDto userPrivateKey(String userPrivateKey) {
        this.userPrivateKey = userPrivateKey;
        return this;
    }

    /**
     * Get userPrivateKey
     *
     * @return userPrivateKey
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    @JsonProperty(JSON_PROPERTY_USER_PRIVATE_KEY)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getUserPrivateKey() {
        return userPrivateKey;
    }


    @JsonProperty(JSON_PROPERTY_USER_PRIVATE_KEY)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setUserPrivateKey(String userPrivateKey) {
        this.userPrivateKey = userPrivateKey;
    }


    public DeviceDto owner(String owner) {
        this.owner = owner;
        return this;
    }

    /**
     * Get owner
     *
     * @return owner
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_OWNER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getOwner() {
        return owner;
    }


    @JsonProperty(JSON_PROPERTY_OWNER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setOwner(String owner) {
        this.owner = owner;
    }


    public DeviceDto creationTime(DateTime creationTime) {
        this.creationTime = creationTime;
        return this;
    }

    /**
     * Get creationTime
     *
     * @return creationTime
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(example = "2022-03-10T16:15:50Z", value = "")
    @JsonProperty(JSON_PROPERTY_CREATION_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public DateTime getCreationTime() {
        return creationTime;
    }


    @JsonProperty(JSON_PROPERTY_CREATION_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCreationTime(DateTime creationTime) {
        this.creationTime = creationTime;
    }


    /**
     * Return true if this DeviceDto object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if(this == o) {
            return true;
        }
        if(o == null || getClass() != o.getClass()) {
            return false;
        }
        DeviceDto deviceDto = (DeviceDto) o;
        return Objects.equals(this.id, deviceDto.id) &&
                Objects.equals(this.name, deviceDto.name) &&
                Objects.equals(this.type, deviceDto.type) &&
                Objects.equals(this.publicKey, deviceDto.publicKey) &&
                Objects.equals(this.userPrivateKey, deviceDto.userPrivateKey) &&
                Objects.equals(this.owner, deviceDto.owner) &&
                Objects.equals(this.creationTime, deviceDto.creationTime);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, type, publicKey, userPrivateKey, owner, creationTime);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DeviceDto {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    publicKey: ").append(toIndentedString(publicKey)).append("\n");
        sb.append("    userPrivateKey: ").append(toIndentedString(userPrivateKey)).append("\n");
        sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
        sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

