/*
 * hub-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.iterate.hub.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;


/**
 * GroupDto
 */
@JsonPropertyOrder({
        GroupDto.JSON_PROPERTY_ID,
        GroupDto.JSON_PROPERTY_TYPE,
        GroupDto.JSON_PROPERTY_NAME,
        GroupDto.JSON_PROPERTY_PICTURE_URL
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GroupDto {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_TYPE = "type";
  private Type type;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_PICTURE_URL = "pictureUrl";
  private String pictureUrl;

    public GroupDto() {
    }

  public GroupDto id(String id) {
    this.id = id;
    return this;
  }

    /**
     * Get id
     *
     * @return id
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getId() {
        return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public GroupDto type(Type type) {
    this.type = type;
    return this;
  }

    /**
     * Get type
     *
     * @return type
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Type getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(Type type) {
    this.type = type;
  }


  public GroupDto name(String name) {
      this.name = name;
      return this;
  }

    /**
     * Get name
     *
     * @return name
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public GroupDto pictureUrl(String pictureUrl) {
      this.pictureUrl = pictureUrl;
      return this;
  }

    /**
     * Get pictureUrl
     *
     * @return pictureUrl
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_PICTURE_URL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPictureUrl() {
    return pictureUrl;
  }


  @JsonProperty(JSON_PROPERTY_PICTURE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPictureUrl(String pictureUrl) {
    this.pictureUrl = pictureUrl;
  }


  /**
   * Return true if this GroupDto object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
      if(this == o) {
          return true;
      }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
      GroupDto groupDto = (GroupDto) o;
      return Objects.equals(this.id, groupDto.id) &&
              Objects.equals(this.type, groupDto.type) &&
              Objects.equals(this.name, groupDto.name) &&
              Objects.equals(this.pictureUrl, groupDto.pictureUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, name, pictureUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pictureUrl: ").append(toIndentedString(pictureUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

