/*
 * hub-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.iterate.hub.client.model;

import org.joda.time.DateTime;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;


/**
 * LicenseUserInfoDto
 */
@JsonPropertyOrder({
        LicenseUserInfoDto.JSON_PROPERTY_LICENSED_SEATS,
        LicenseUserInfoDto.JSON_PROPERTY_USED_SEATS,
        LicenseUserInfoDto.JSON_PROPERTY_EXPIRES_AT
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class LicenseUserInfoDto {
    public static final String JSON_PROPERTY_LICENSED_SEATS = "licensedSeats";
    private Integer licensedSeats;

    public static final String JSON_PROPERTY_USED_SEATS = "usedSeats";
    private Integer usedSeats;

    public static final String JSON_PROPERTY_EXPIRES_AT = "expiresAt";
    private DateTime expiresAt;

    public LicenseUserInfoDto() {
    }

    public LicenseUserInfoDto licensedSeats(Integer licensedSeats) {
        this.licensedSeats = licensedSeats;
        return this;
    }

    /**
     * Get licensedSeats
     *
     * @return licensedSeats
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_LICENSED_SEATS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getLicensedSeats() {
        return licensedSeats;
    }


    @JsonProperty(JSON_PROPERTY_LICENSED_SEATS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLicensedSeats(Integer licensedSeats) {
        this.licensedSeats = licensedSeats;
    }


    public LicenseUserInfoDto usedSeats(Integer usedSeats) {
        this.usedSeats = usedSeats;
        return this;
    }

    /**
     * Get usedSeats
     *
     * @return usedSeats
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_USED_SEATS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getUsedSeats() {
        return usedSeats;
    }


    @JsonProperty(JSON_PROPERTY_USED_SEATS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUsedSeats(Integer usedSeats) {
        this.usedSeats = usedSeats;
    }


    public LicenseUserInfoDto expiresAt(DateTime expiresAt) {
        this.expiresAt = expiresAt;
        return this;
    }

    /**
     * Get expiresAt
     *
     * @return expiresAt
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(example = "2022-03-10T16:15:50Z", value = "")
    @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public DateTime getExpiresAt() {
        return expiresAt;
    }


    @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setExpiresAt(DateTime expiresAt) {
        this.expiresAt = expiresAt;
    }


    /**
     * Return true if this LicenseUserInfoDto object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if(this == o) {
            return true;
        }
        if(o == null || getClass() != o.getClass()) {
            return false;
        }
        LicenseUserInfoDto licenseUserInfoDto = (LicenseUserInfoDto) o;
        return Objects.equals(this.licensedSeats, licenseUserInfoDto.licensedSeats) &&
                Objects.equals(this.usedSeats, licenseUserInfoDto.usedSeats) &&
                Objects.equals(this.expiresAt, licenseUserInfoDto.expiresAt);
    }

    @Override
    public int hashCode() {
        return Objects.hash(licensedSeats, usedSeats, expiresAt);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class LicenseUserInfoDto {\n");
        sb.append("    licensedSeats: ").append(toIndentedString(licensedSeats)).append("\n");
        sb.append("    usedSeats: ").append(toIndentedString(usedSeats)).append("\n");
        sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if(o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
  }

}

