/*
 * hub-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.iterate.hub.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;


/**
 * MemberDto
 */
@JsonPropertyOrder({
        MemberDto.JSON_PROPERTY_ID,
        MemberDto.JSON_PROPERTY_TYPE,
        MemberDto.JSON_PROPERTY_NAME,
        MemberDto.JSON_PROPERTY_PICTURE_URL,
        MemberDto.JSON_PROPERTY_ECDH_PUBLIC_KEY,
        MemberDto.JSON_PROPERTY_ECDSA_PUBLIC_KEY,
        MemberDto.JSON_PROPERTY_ROLE
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class MemberDto {
    public static final String JSON_PROPERTY_ID = "id";
    private String id;

    public static final String JSON_PROPERTY_TYPE = "type";
    private Type type;

    public static final String JSON_PROPERTY_NAME = "name";
    private String name;

    public static final String JSON_PROPERTY_PICTURE_URL = "pictureUrl";
    private String pictureUrl;

    public static final String JSON_PROPERTY_ECDH_PUBLIC_KEY = "ecdhPublicKey";
    private String ecdhPublicKey;

    public static final String JSON_PROPERTY_ECDSA_PUBLIC_KEY = "ecdsaPublicKey";
    private String ecdsaPublicKey;

    public static final String JSON_PROPERTY_ROLE = "role";
    private Role role;

    public MemberDto() {
    }

    public MemberDto id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getId() {
        return id;
    }


    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setId(String id) {
        this.id = id;
    }


    public MemberDto type(Type type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Type getType() {
        return type;
    }


    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setType(Type type) {
        this.type = type;
    }


    public MemberDto name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getName() {
        return name;
    }


    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setName(String name) {
        this.name = name;
    }


    public MemberDto pictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl;
        return this;
    }

    /**
     * Get pictureUrl
     *
     * @return pictureUrl
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_PICTURE_URL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPictureUrl() {
        return pictureUrl;
    }


    @JsonProperty(JSON_PROPERTY_PICTURE_URL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl;
    }


    public MemberDto ecdhPublicKey(String ecdhPublicKey) {
        this.ecdhPublicKey = ecdhPublicKey;
        return this;
    }

    /**
     * Get ecdhPublicKey
     *
     * @return ecdhPublicKey
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_ECDH_PUBLIC_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getEcdhPublicKey() {
        return ecdhPublicKey;
    }


    @JsonProperty(JSON_PROPERTY_ECDH_PUBLIC_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEcdhPublicKey(String ecdhPublicKey) {
        this.ecdhPublicKey = ecdhPublicKey;
    }


    public MemberDto ecdsaPublicKey(String ecdsaPublicKey) {
        this.ecdsaPublicKey = ecdsaPublicKey;
        return this;
    }

    /**
     * Get ecdsaPublicKey
     *
     * @return ecdsaPublicKey
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_ECDSA_PUBLIC_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getEcdsaPublicKey() {
        return ecdsaPublicKey;
    }


    @JsonProperty(JSON_PROPERTY_ECDSA_PUBLIC_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEcdsaPublicKey(String ecdsaPublicKey) {
        this.ecdsaPublicKey = ecdsaPublicKey;
    }


    public MemberDto role(Role role) {
        this.role = role;
        return this;
    }

    /**
     * Get role
     *
     * @return role
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_ROLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Role getRole() {
        return role;
    }


    @JsonProperty(JSON_PROPERTY_ROLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRole(Role role) {
        this.role = role;
    }


    /**
     * Return true if this MemberDto object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if(this == o) {
            return true;
        }
        if(o == null || getClass() != o.getClass()) {
            return false;
        }
        MemberDto memberDto = (MemberDto) o;
        return Objects.equals(this.id, memberDto.id) &&
                Objects.equals(this.type, memberDto.type) &&
                Objects.equals(this.name, memberDto.name) &&
                Objects.equals(this.pictureUrl, memberDto.pictureUrl) &&
                Objects.equals(this.ecdhPublicKey, memberDto.ecdhPublicKey) &&
                Objects.equals(this.ecdsaPublicKey, memberDto.ecdsaPublicKey) &&
                Objects.equals(this.role, memberDto.role);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, type, name, pictureUrl, ecdhPublicKey, ecdsaPublicKey, role);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MemberDto {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    pictureUrl: ").append(toIndentedString(pictureUrl)).append("\n");
        sb.append("    ecdhPublicKey: ").append(toIndentedString(ecdhPublicKey)).append("\n");
        sb.append("    ecdsaPublicKey: ").append(toIndentedString(ecdsaPublicKey)).append("\n");
        sb.append("    role: ").append(toIndentedString(role)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

