/*
 * hub-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.iterate.hub.client.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets S3_STORAGE_CLASSES
 */
public enum S3STORAGECLASSES {

    STANDARD("STANDARD"),

    INTELLIGENT_TIERING("INTELLIGENT_TIERING"),

    STANDARD_IA("STANDARD_IA"),

    ONEZONE_IA("ONEZONE_IA"),

    REDUCED_REDUNDANCY("REDUCED_REDUNDANCY"),

    GLACIER("GLACIER"),

    GLACIER_IR("GLACIER_IR"),

    DEEP_ARCHIVE("DEEP_ARCHIVE");

    private String value;

    S3STORAGECLASSES(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
    public static S3STORAGECLASSES fromValue(String value) {
        for(S3STORAGECLASSES b : S3STORAGECLASSES.values()) {
            if(b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
}

