/*
 * hub-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.iterate.hub.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;


/**
 * SettingsDto
 */
@JsonPropertyOrder({
        SettingsDto.JSON_PROPERTY_HUB_ID,
        SettingsDto.JSON_PROPERTY_WOT_MAX_DEPTH,
        SettingsDto.JSON_PROPERTY_WOT_ID_VERIFY_LEN
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SettingsDto {
    public static final String JSON_PROPERTY_HUB_ID = "hubId";
    private String hubId;

    public static final String JSON_PROPERTY_WOT_MAX_DEPTH = "wotMaxDepth";
    private Integer wotMaxDepth;

    public static final String JSON_PROPERTY_WOT_ID_VERIFY_LEN = "wotIdVerifyLen";
    private Integer wotIdVerifyLen;

    public SettingsDto() {
    }

    public SettingsDto hubId(String hubId) {
        this.hubId = hubId;
        return this;
    }

    /**
     * Get hubId
     *
     * @return hubId
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_HUB_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getHubId() {
        return hubId;
    }


    @JsonProperty(JSON_PROPERTY_HUB_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setHubId(String hubId) {
        this.hubId = hubId;
    }


    public SettingsDto wotMaxDepth(Integer wotMaxDepth) {
        this.wotMaxDepth = wotMaxDepth;
        return this;
    }

    /**
     * Get wotMaxDepth
     * minimum: 0
     * maximum: 9
     *
     * @return wotMaxDepth
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_WOT_MAX_DEPTH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getWotMaxDepth() {
        return wotMaxDepth;
    }


    @JsonProperty(JSON_PROPERTY_WOT_MAX_DEPTH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setWotMaxDepth(Integer wotMaxDepth) {
        this.wotMaxDepth = wotMaxDepth;
    }


    public SettingsDto wotIdVerifyLen(Integer wotIdVerifyLen) {
        this.wotIdVerifyLen = wotIdVerifyLen;
        return this;
    }

    /**
     * Get wotIdVerifyLen
     * minimum: 0
     *
     * @return wotIdVerifyLen
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_WOT_ID_VERIFY_LEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getWotIdVerifyLen() {
        return wotIdVerifyLen;
    }


    @JsonProperty(JSON_PROPERTY_WOT_ID_VERIFY_LEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setWotIdVerifyLen(Integer wotIdVerifyLen) {
        this.wotIdVerifyLen = wotIdVerifyLen;
    }


    /**
     * Return true if this SettingsDto object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if(this == o) {
            return true;
        }
        if(o == null || getClass() != o.getClass()) {
            return false;
        }
        SettingsDto settingsDto = (SettingsDto) o;
        return Objects.equals(this.hubId, settingsDto.hubId) &&
                Objects.equals(this.wotMaxDepth, settingsDto.wotMaxDepth) &&
                Objects.equals(this.wotIdVerifyLen, settingsDto.wotIdVerifyLen);
    }

    @Override
    public int hashCode() {
        return Objects.hash(hubId, wotMaxDepth, wotIdVerifyLen);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SettingsDto {\n");
        sb.append("    hubId: ").append(toIndentedString(hubId)).append("\n");
        sb.append("    wotMaxDepth: ").append(toIndentedString(wotMaxDepth)).append("\n");
        sb.append("    wotIdVerifyLen: ").append(toIndentedString(wotIdVerifyLen)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if(o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
  }

}

