/*
 * hub-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.iterate.hub.client.model;

import org.openapitools.jackson.nullable.JsonNullable;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;


/**
 * StorageProfileS3STSDto
 */
@JsonPropertyOrder({
        StorageProfileS3STSDto.JSON_PROPERTY_ID,
        StorageProfileS3STSDto.JSON_PROPERTY_NAME,
        StorageProfileS3STSDto.JSON_PROPERTY_PROTOCOL,
        StorageProfileS3STSDto.JSON_PROPERTY_ARCHIVED,
        StorageProfileS3STSDto.JSON_PROPERTY_SCHEME,
        StorageProfileS3STSDto.JSON_PROPERTY_HOSTNAME,
        StorageProfileS3STSDto.JSON_PROPERTY_PORT,
        StorageProfileS3STSDto.JSON_PROPERTY_WITH_PATH_STYLE_ACCESS_ENABLED,
        StorageProfileS3STSDto.JSON_PROPERTY_STORAGE_CLASS,
        StorageProfileS3STSDto.JSON_PROPERTY_REGION,
        StorageProfileS3STSDto.JSON_PROPERTY_REGIONS,
        StorageProfileS3STSDto.JSON_PROPERTY_BUCKET_PREFIX,
        StorageProfileS3STSDto.JSON_PROPERTY_STS_ROLE_ARN_CLIENT,
        StorageProfileS3STSDto.JSON_PROPERTY_STS_ROLE_ARN_HUB,
        StorageProfileS3STSDto.JSON_PROPERTY_STS_ENDPOINT,
        StorageProfileS3STSDto.JSON_PROPERTY_BUCKET_VERSIONING,
        StorageProfileS3STSDto.JSON_PROPERTY_BUCKET_ACCELERATION,
        StorageProfileS3STSDto.JSON_PROPERTY_BUCKET_ENCRYPTION,
        StorageProfileS3STSDto.JSON_PROPERTY_STS_ROLE_ARN,
        StorageProfileS3STSDto.JSON_PROPERTY_STS_ROLE_ARN2,
        StorageProfileS3STSDto.JSON_PROPERTY_STS_DURATION_SECONDS
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class StorageProfileS3STSDto {
    public static final String JSON_PROPERTY_ID = "id";
    private UUID id;

    public static final String JSON_PROPERTY_NAME = "name";
    private String name;

    public static final String JSON_PROPERTY_PROTOCOL = "protocol";
    private Protocol protocol;

    public static final String JSON_PROPERTY_ARCHIVED = "archived";
    private Boolean archived;

    public static final String JSON_PROPERTY_SCHEME = "scheme";
    private JsonNullable<String> scheme = JsonNullable.<String>undefined();

    public static final String JSON_PROPERTY_HOSTNAME = "hostname";
    private JsonNullable<String> hostname = JsonNullable.<String>undefined();

    public static final String JSON_PROPERTY_PORT = "port";
    private JsonNullable<Integer> port = JsonNullable.<Integer>undefined();

    public static final String JSON_PROPERTY_WITH_PATH_STYLE_ACCESS_ENABLED = "withPathStyleAccessEnabled";
    private Boolean withPathStyleAccessEnabled = false;

    public static final String JSON_PROPERTY_STORAGE_CLASS = "storageClass";
    private S3STORAGECLASSES storageClass;

    public static final String JSON_PROPERTY_REGION = "region";
    private String region = "us-east-1";

    public static final String JSON_PROPERTY_REGIONS = "regions";
    private List<String> regions = new ArrayList<>();

    public static final String JSON_PROPERTY_BUCKET_PREFIX = "bucketPrefix";
    private String bucketPrefix;

    public static final String JSON_PROPERTY_STS_ROLE_ARN_CLIENT = "stsRoleArnClient";
    private String stsRoleArnClient;

    public static final String JSON_PROPERTY_STS_ROLE_ARN_HUB = "stsRoleArnHub";
    private String stsRoleArnHub;

    public static final String JSON_PROPERTY_STS_ENDPOINT = "stsEndpoint";
    private JsonNullable<String> stsEndpoint = JsonNullable.<String>undefined();

    public static final String JSON_PROPERTY_BUCKET_VERSIONING = "bucketVersioning";
    private Boolean bucketVersioning = true;

    public static final String JSON_PROPERTY_BUCKET_ACCELERATION = "bucketAcceleration";
    private JsonNullable<Boolean> bucketAcceleration = JsonNullable.<Boolean>undefined();

    public static final String JSON_PROPERTY_BUCKET_ENCRYPTION = "bucketEncryption";
    private S3SERVERSIDEENCRYPTION bucketEncryption;

    public static final String JSON_PROPERTY_STS_ROLE_ARN = "stsRoleArn";
    private String stsRoleArn;

    public static final String JSON_PROPERTY_STS_ROLE_ARN2 = "stsRoleArn2";
    private JsonNullable<String> stsRoleArn2 = JsonNullable.<String>undefined();

    public static final String JSON_PROPERTY_STS_DURATION_SECONDS = "stsDurationSeconds";
    private JsonNullable<Integer> stsDurationSeconds = JsonNullable.<Integer>undefined();

    public StorageProfileS3STSDto() {
    }

    public StorageProfileS3STSDto id(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Technical identifier for a storage profile. Must be unique UUID. Clients will use this as vendor in profile and provider in vault bookmark
     *
     * @return id
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "Technical identifier for a storage profile. Must be unique UUID. Clients will use this as vendor in profile and provider in vault bookmark")
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public UUID getId() {
        return id;
    }


    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setId(UUID id) {
        this.id = id;
    }


    public StorageProfileS3STSDto name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Displayed when choosing type of a new vault in dropdown.
     *
     * @return name
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "Displayed when choosing type of a new vault in dropdown.")
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getName() {
        return name;
    }


    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setName(String name) {
        this.name = name;
    }


    public StorageProfileS3STSDto protocol(Protocol protocol) {
        this.protocol = protocol;
        return this;
    }

    /**
     * Storage protocol: S3 (permanent credentials) or S3STS (STS).
     *
     * @return protocol
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "Storage protocol: S3 (permanent credentials) or S3STS (STS).")
    @JsonProperty(JSON_PROPERTY_PROTOCOL)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public Protocol getProtocol() {
        return protocol;
    }


    @JsonProperty(JSON_PROPERTY_PROTOCOL)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setProtocol(Protocol protocol) {
        this.protocol = protocol;
    }


    public StorageProfileS3STSDto archived(Boolean archived) {
        this.archived = archived;
        return this;
    }

    /**
     * For archived storage profiles, no vaults can be created any more.
     *
     * @return archived
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "For archived storage profiles, no vaults can be created any more.")
    @JsonProperty(JSON_PROPERTY_ARCHIVED)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public Boolean getArchived() {
        return archived;
    }


    @JsonProperty(JSON_PROPERTY_ARCHIVED)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setArchived(Boolean archived) {
        this.archived = archived;
    }


    public StorageProfileS3STSDto scheme(String scheme) {
        this.scheme = JsonNullable.<String>of(scheme);
        return this;
    }

    /**
     * Scheme of S3 endpoint for template upload/bucket creation. Defaults to default for protocol, i.e. https in most cases.
     *
     * @return scheme
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(example = "https", value = "Scheme of S3 endpoint for template upload/bucket creation. Defaults to default for protocol, i.e. https in most cases.")
  @JsonIgnore

    public String getScheme() {
        return scheme.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_SCHEME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<String> getScheme_JsonNullable() {
        return scheme;
    }

    @JsonProperty(JSON_PROPERTY_SCHEME)
    public void setScheme_JsonNullable(JsonNullable<String> scheme) {
        this.scheme = scheme;
    }

    public void setScheme(String scheme) {
        this.scheme = JsonNullable.<String>of(scheme);
    }


    public StorageProfileS3STSDto hostname(String hostname) {
        this.hostname = JsonNullable.<String>of(hostname);
        return this;
    }

    /**
     * Hostname S3 endpoint for template upload/bucket creation. Defaults to AWS SDK default.
     *
     * @return hostname
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(example = "s3-us-gov-west-1.amazonaws.com", value = "Hostname S3 endpoint for template upload/bucket creation. Defaults to AWS SDK default.")
    @JsonIgnore

    public String getHostname() {
        return hostname.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_HOSTNAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<String> getHostname_JsonNullable() {
        return hostname;
    }

    @JsonProperty(JSON_PROPERTY_HOSTNAME)
    public void setHostname_JsonNullable(JsonNullable<String> hostname) {
        this.hostname = hostname;
    }

    public void setHostname(String hostname) {
        this.hostname = JsonNullable.<String>of(hostname);
    }


    public StorageProfileS3STSDto port(Integer port) {
        this.port = JsonNullable.<Integer>of(port);
        return this;
    }

    /**
     * Port S3 endpoint for template upload/bucket creation. Defaults to default port for scheme.
     *
     * @return port
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(example = "443", value = "Port S3 endpoint for template upload/bucket creation. Defaults to default port for scheme.")
    @JsonIgnore

    public Integer getPort() {
        return port.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_PORT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<Integer> getPort_JsonNullable() {
        return port;
    }

    @JsonProperty(JSON_PROPERTY_PORT)
    public void setPort_JsonNullable(JsonNullable<Integer> port) {
        this.port = port;
    }

    public void setPort(Integer port) {
        this.port = JsonNullable.<Integer>of(port);
    }


    public StorageProfileS3STSDto withPathStyleAccessEnabled(Boolean withPathStyleAccessEnabled) {
        this.withPathStyleAccessEnabled = withPathStyleAccessEnabled;
        return this;
    }

    /**
     * Whether to use path style for S3 endpoint for template upload/bucket creation.
     *
     * @return withPathStyleAccessEnabled
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(example = "false", value = "Whether to use path style for S3 endpoint for template upload/bucket creation.")
    @JsonProperty(JSON_PROPERTY_WITH_PATH_STYLE_ACCESS_ENABLED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getWithPathStyleAccessEnabled() {
        return withPathStyleAccessEnabled;
    }


    @JsonProperty(JSON_PROPERTY_WITH_PATH_STYLE_ACCESS_ENABLED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setWithPathStyleAccessEnabled(Boolean withPathStyleAccessEnabled) {
        this.withPathStyleAccessEnabled = withPathStyleAccessEnabled;
    }


    public StorageProfileS3STSDto storageClass(S3STORAGECLASSES storageClass) {
        this.storageClass = storageClass;
        return this;
    }

    /**
     * Storage class for upload. Defaults to STANDARD
     *
     * @return storageClass
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(example = "STANDARD", required = true, value = "Storage class for upload. Defaults to STANDARD")
    @JsonProperty(JSON_PROPERTY_STORAGE_CLASS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public S3STORAGECLASSES getStorageClass() {
        return storageClass;
    }


    @JsonProperty(JSON_PROPERTY_STORAGE_CLASS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setStorageClass(S3STORAGECLASSES storageClass) {
        this.storageClass = storageClass;
    }


    public StorageProfileS3STSDto region(String region) {
        this.region = region;
        return this;
    }

    /**
     * Default region selected in the frontend/client to create bucket in.
     *
     * @return region
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(example = "443", required = true, value = "Default region selected in the frontend/client to create bucket in.")
    @JsonProperty(JSON_PROPERTY_REGION)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getRegion() {
        return region;
    }


    @JsonProperty(JSON_PROPERTY_REGION)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setRegion(String region) {
        this.region = region;
    }


    public StorageProfileS3STSDto regions(List<String> regions) {
        this.regions = regions;
        return this;
    }

    public StorageProfileS3STSDto addRegionsItem(String regionsItem) {
        this.regions.add(regionsItem);
        return this;
    }

    /**
     * List of selectable regions in the frontend/client to create bucket in. Defaults to full list from AWS SDK.
     *
     * @return regions
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "List of selectable regions in the frontend/client to create bucket in. Defaults to full list from AWS SDK.")
    @JsonProperty(JSON_PROPERTY_REGIONS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public List<String> getRegions() {
        return regions;
    }


    @JsonProperty(JSON_PROPERTY_REGIONS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setRegions(List<String> regions) {
        this.regions = regions;
    }


    public StorageProfileS3STSDto bucketPrefix(String bucketPrefix) {
        this.bucketPrefix = bucketPrefix;
        return this;
    }

    /**
     * Buckets are create with name &lt;bucket prefix&gt;&lt;vault UUID&gt;.
     *
     * @return bucketPrefix
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(example = "cipherduck", required = true, value = "Buckets are create with name <bucket prefix><vault UUID>.")
    @JsonProperty(JSON_PROPERTY_BUCKET_PREFIX)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getBucketPrefix() {
        return bucketPrefix;
    }


    @JsonProperty(JSON_PROPERTY_BUCKET_PREFIX)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setBucketPrefix(String bucketPrefix) {
        this.bucketPrefix = bucketPrefix;
    }


    public StorageProfileS3STSDto stsRoleArnClient(String stsRoleArnClient) {
        this.stsRoleArnClient = stsRoleArnClient;
        return this;
    }

    /**
     * STS role for clients to assume to create buckets. Will be the same as stsRoleArnHub for AWS, different for MinIO.
     *
     * @return stsRoleArnClient
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(example = "arn:aws:iam::<ACCOUNT ID>:role/cipherduck-createbucket", required = true, value = "STS role for clients to assume to create buckets. Will be the same as stsRoleArnHub for AWS, different for MinIO.")
    @JsonProperty(JSON_PROPERTY_STS_ROLE_ARN_CLIENT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getStsRoleArnClient() {
        return stsRoleArnClient;
    }


    @JsonProperty(JSON_PROPERTY_STS_ROLE_ARN_CLIENT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setStsRoleArnClient(String stsRoleArnClient) {
        this.stsRoleArnClient = stsRoleArnClient;
    }


    public StorageProfileS3STSDto stsRoleArnHub(String stsRoleArnHub) {
        this.stsRoleArnHub = stsRoleArnHub;
        return this;
    }

    /**
     * STS role for frontend to assume to create buckets (used with inline policy and passed to hub storage). Will be the same as stsRoleArnClient for AWS, different for MinIO.
     *
     * @return stsRoleArnHub
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(example = "arn:aws:iam::<ACCOUNT ID>:role/cipherduck-createbucket", required = true, value = "STS role for frontend to assume to create buckets (used with inline policy and passed to hub storage). Will be the same as stsRoleArnClient for AWS, different for MinIO.")
    @JsonProperty(JSON_PROPERTY_STS_ROLE_ARN_HUB)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getStsRoleArnHub() {
        return stsRoleArnHub;
    }


    @JsonProperty(JSON_PROPERTY_STS_ROLE_ARN_HUB)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setStsRoleArnHub(String stsRoleArnHub) {
        this.stsRoleArnHub = stsRoleArnHub;
    }


    public StorageProfileS3STSDto stsEndpoint(String stsEndpoint) {
        this.stsEndpoint = JsonNullable.<String>of(stsEndpoint);
        return this;
    }

    /**
     * STS endpoint to use for AssumeRoleWithWebIdentity and AssumeRole for getting a temporary access token passed to the storage. Defaults to AWS SDK default.
     *
     * @return stsEndpoint
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "STS endpoint to use for AssumeRoleWithWebIdentity and AssumeRole for getting a temporary access token passed to the storage. Defaults to AWS SDK default.")
    @JsonIgnore

    public String getStsEndpoint() {
        return stsEndpoint.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_STS_ENDPOINT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<String> getStsEndpoint_JsonNullable() {
        return stsEndpoint;
    }

    @JsonProperty(JSON_PROPERTY_STS_ENDPOINT)
    public void setStsEndpoint_JsonNullable(JsonNullable<String> stsEndpoint) {
        this.stsEndpoint = stsEndpoint;
    }

    public void setStsEndpoint(String stsEndpoint) {
        this.stsEndpoint = JsonNullable.<String>of(stsEndpoint);
    }


    public StorageProfileS3STSDto bucketVersioning(Boolean bucketVersioning) {
        this.bucketVersioning = bucketVersioning;
        return this;
    }

    /**
     * Enable bucket versioning upon bucket creation
     *
     * @return bucketVersioning
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "Enable bucket versioning upon bucket creation")
    @JsonProperty(JSON_PROPERTY_BUCKET_VERSIONING)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public Boolean getBucketVersioning() {
        return bucketVersioning;
    }


    @JsonProperty(JSON_PROPERTY_BUCKET_VERSIONING)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setBucketVersioning(Boolean bucketVersioning) {
        this.bucketVersioning = bucketVersioning;
    }


    public StorageProfileS3STSDto bucketAcceleration(Boolean bucketAcceleration) {
        this.bucketAcceleration = JsonNullable.<Boolean>of(bucketAcceleration);
        return this;
    }

    /**
     * Enable bucket versioning upon bucket creation (null for MinIO)
     * @return bucketAcceleration
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Enable bucket versioning upon bucket creation (null for MinIO)")
    @JsonIgnore

    public Boolean getBucketAcceleration() {
        return bucketAcceleration.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_BUCKET_ACCELERATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<Boolean> getBucketAcceleration_JsonNullable() {
        return bucketAcceleration;
    }

    @JsonProperty(JSON_PROPERTY_BUCKET_ACCELERATION)
    public void setBucketAcceleration_JsonNullable(JsonNullable<Boolean> bucketAcceleration) {
        this.bucketAcceleration = bucketAcceleration;
    }

    public void setBucketAcceleration(Boolean bucketAcceleration) {
        this.bucketAcceleration = JsonNullable.<Boolean>of(bucketAcceleration);
    }


    public StorageProfileS3STSDto bucketEncryption(S3SERVERSIDEENCRYPTION bucketEncryption) {
        this.bucketEncryption = bucketEncryption;
        return this;
    }

    /**
     * Enable bucket versioning upon bucket creation
     * @return bucketEncryption
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "Enable bucket versioning upon bucket creation")
    @JsonProperty(JSON_PROPERTY_BUCKET_ENCRYPTION)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public S3SERVERSIDEENCRYPTION getBucketEncryption() {
        return bucketEncryption;
    }


    @JsonProperty(JSON_PROPERTY_BUCKET_ENCRYPTION)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setBucketEncryption(S3SERVERSIDEENCRYPTION bucketEncryption) {
        this.bucketEncryption = bucketEncryption;
    }


    public StorageProfileS3STSDto stsRoleArn(String stsRoleArn) {
        this.stsRoleArn = stsRoleArn;
        return this;
    }

    /**
     * roleArn to for STS AssumeRoleWithWebIdentity (AWS and MinIO)
     *
     * @return stsRoleArn
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(example = "arn:aws:iam::930717317329:role/cipherduck_chain_01", required = true, value = "roleArn to for STS AssumeRoleWithWebIdentity (AWS and MinIO)")
    @JsonProperty(JSON_PROPERTY_STS_ROLE_ARN)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getStsRoleArn() {
        return stsRoleArn;
    }


    @JsonProperty(JSON_PROPERTY_STS_ROLE_ARN)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setStsRoleArn(String stsRoleArn) {
        this.stsRoleArn = stsRoleArn;
    }


    public StorageProfileS3STSDto stsRoleArn2(String stsRoleArn2) {
        this.stsRoleArn2 = JsonNullable.<String>of(stsRoleArn2);
        return this;
    }

    /**
     * roleArn to assume for STS AssumeRole in role chaining (AWS only, not MinIO)
     *
     * @return stsRoleArn2
     **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "arn:aws:iam::930717317329:role/cipherduck_chain_02", value = "roleArn to assume for STS AssumeRole in role chaining (AWS only, not MinIO)")
  @JsonIgnore

  public String getStsRoleArn2() {
      return stsRoleArn2.orElse(null);
  }

    @JsonProperty(JSON_PROPERTY_STS_ROLE_ARN2)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<String> getStsRoleArn2_JsonNullable() {
        return stsRoleArn2;
    }

    @JsonProperty(JSON_PROPERTY_STS_ROLE_ARN2)
    public void setStsRoleArn2_JsonNullable(JsonNullable<String> stsRoleArn2) {
        this.stsRoleArn2 = stsRoleArn2;
    }

    public void setStsRoleArn2(String stsRoleArn2) {
        this.stsRoleArn2 = JsonNullable.<String>of(stsRoleArn2);
    }


    public StorageProfileS3STSDto stsDurationSeconds(Integer stsDurationSeconds) {
        this.stsDurationSeconds = JsonNullable.<Integer>of(stsDurationSeconds);
        return this;
    }

    /**
     * Token lifetime for STS tokens assumed. Defaults to AWS/MinIO defaults
   * @return stsDurationSeconds
  **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Token lifetime for STS tokens assumed. Defaults to AWS/MinIO defaults")
    @JsonIgnore

    public Integer getStsDurationSeconds() {
        return stsDurationSeconds.orElse(null);
    }

    @JsonProperty(JSON_PROPERTY_STS_DURATION_SECONDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public JsonNullable<Integer> getStsDurationSeconds_JsonNullable() {
        return stsDurationSeconds;
    }

    @JsonProperty(JSON_PROPERTY_STS_DURATION_SECONDS)
    public void setStsDurationSeconds_JsonNullable(JsonNullable<Integer> stsDurationSeconds) {
        this.stsDurationSeconds = stsDurationSeconds;
    }

    public void setStsDurationSeconds(Integer stsDurationSeconds) {
        this.stsDurationSeconds = JsonNullable.<Integer>of(stsDurationSeconds);
    }


    /**
     * Return true if this StorageProfileS3STSDto object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if(this == o) {
            return true;
        }
        if(o == null || getClass() != o.getClass()) {
            return false;
        }
        StorageProfileS3STSDto storageProfileS3STSDto = (StorageProfileS3STSDto) o;
        return Objects.equals(this.id, storageProfileS3STSDto.id) &&
                Objects.equals(this.name, storageProfileS3STSDto.name) &&
                Objects.equals(this.protocol, storageProfileS3STSDto.protocol) &&
                Objects.equals(this.archived, storageProfileS3STSDto.archived) &&
                equalsNullable(this.scheme, storageProfileS3STSDto.scheme) &&
                equalsNullable(this.hostname, storageProfileS3STSDto.hostname) &&
                equalsNullable(this.port, storageProfileS3STSDto.port) &&
                Objects.equals(this.withPathStyleAccessEnabled, storageProfileS3STSDto.withPathStyleAccessEnabled) &&
                Objects.equals(this.storageClass, storageProfileS3STSDto.storageClass) &&
                Objects.equals(this.region, storageProfileS3STSDto.region) &&
                Objects.equals(this.regions, storageProfileS3STSDto.regions) &&
                Objects.equals(this.bucketPrefix, storageProfileS3STSDto.bucketPrefix) &&
                Objects.equals(this.stsRoleArnClient, storageProfileS3STSDto.stsRoleArnClient) &&
                Objects.equals(this.stsRoleArnHub, storageProfileS3STSDto.stsRoleArnHub) &&
                equalsNullable(this.stsEndpoint, storageProfileS3STSDto.stsEndpoint) &&
                Objects.equals(this.bucketVersioning, storageProfileS3STSDto.bucketVersioning) &&
                equalsNullable(this.bucketAcceleration, storageProfileS3STSDto.bucketAcceleration) &&
                Objects.equals(this.bucketEncryption, storageProfileS3STSDto.bucketEncryption) &&
                Objects.equals(this.stsRoleArn, storageProfileS3STSDto.stsRoleArn) &&
                equalsNullable(this.stsRoleArn2, storageProfileS3STSDto.stsRoleArn2) &&
                equalsNullable(this.stsDurationSeconds, storageProfileS3STSDto.stsDurationSeconds);
    }

    private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
        return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, protocol, archived, hashCodeNullable(scheme), hashCodeNullable(hostname), hashCodeNullable(port), withPathStyleAccessEnabled, storageClass, region, regions, bucketPrefix, stsRoleArnClient, stsRoleArnHub, hashCodeNullable(stsEndpoint), bucketVersioning, hashCodeNullable(bucketAcceleration), bucketEncryption, stsRoleArn, hashCodeNullable(stsRoleArn2), hashCodeNullable(stsDurationSeconds));
    }

    private static <T> int hashCodeNullable(JsonNullable<T> a) {
        if(a == null) {
            return 1;
        }
        return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class StorageProfileS3STSDto {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
        sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
        sb.append("    scheme: ").append(toIndentedString(scheme)).append("\n");
        sb.append("    hostname: ").append(toIndentedString(hostname)).append("\n");
        sb.append("    port: ").append(toIndentedString(port)).append("\n");
        sb.append("    withPathStyleAccessEnabled: ").append(toIndentedString(withPathStyleAccessEnabled)).append("\n");
        sb.append("    storageClass: ").append(toIndentedString(storageClass)).append("\n");
        sb.append("    region: ").append(toIndentedString(region)).append("\n");
        sb.append("    regions: ").append(toIndentedString(regions)).append("\n");
        sb.append("    bucketPrefix: ").append(toIndentedString(bucketPrefix)).append("\n");
        sb.append("    stsRoleArnClient: ").append(toIndentedString(stsRoleArnClient)).append("\n");
        sb.append("    stsRoleArnHub: ").append(toIndentedString(stsRoleArnHub)).append("\n");
        sb.append("    stsEndpoint: ").append(toIndentedString(stsEndpoint)).append("\n");
        sb.append("    bucketVersioning: ").append(toIndentedString(bucketVersioning)).append("\n");
        sb.append("    bucketAcceleration: ").append(toIndentedString(bucketAcceleration)).append("\n");
        sb.append("    bucketEncryption: ").append(toIndentedString(bucketEncryption)).append("\n");
        sb.append("    stsRoleArn: ").append(toIndentedString(stsRoleArn)).append("\n");
        sb.append("    stsRoleArn2: ").append(toIndentedString(stsRoleArn2)).append("\n");
        sb.append("    stsDurationSeconds: ").append(toIndentedString(stsDurationSeconds)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

