/*
 * hub-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ch.iterate.hub.client.model;

import java.util.LinkedHashSet;
import java.util.Objects;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.swagger.annotations.ApiModelProperty;


/**
 * UserDto
 */
@JsonPropertyOrder({
        UserDto.JSON_PROPERTY_ID,
        UserDto.JSON_PROPERTY_TYPE,
        UserDto.JSON_PROPERTY_NAME,
        UserDto.JSON_PROPERTY_PICTURE_URL,
        UserDto.JSON_PROPERTY_EMAIL,
        UserDto.JSON_PROPERTY_DEVICES,
        UserDto.JSON_PROPERTY_ECDH_PUBLIC_KEY,
        UserDto.JSON_PROPERTY_ECDSA_PUBLIC_KEY,
        UserDto.JSON_PROPERTY_PRIVATE_KEY,
        UserDto.JSON_PROPERTY_SETUP_CODE,
        UserDto.JSON_PROPERTY_PUBLIC_KEY
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UserDto {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_TYPE = "type";
  private Type type;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_PICTURE_URL = "pictureUrl";
  private String pictureUrl;

  public static final String JSON_PROPERTY_EMAIL = "email";
  private String email;

  public static final String JSON_PROPERTY_DEVICES = "devices";
  private Set<DeviceDto> devices = null;

  public static final String JSON_PROPERTY_ECDH_PUBLIC_KEY = "ecdhPublicKey";
  private String ecdhPublicKey;

  public static final String JSON_PROPERTY_ECDSA_PUBLIC_KEY = "ecdsaPublicKey";
  private String ecdsaPublicKey;

  public static final String JSON_PROPERTY_PRIVATE_KEY = "privateKey";
  private String privateKey;

  public static final String JSON_PROPERTY_SETUP_CODE = "setupCode";
  private String setupCode;

  public static final String JSON_PROPERTY_PUBLIC_KEY = "publicKey";
  private String publicKey;

    public UserDto() {
  }

  public UserDto id(String id) {
    this.id = id;
    return this;
  }

    /**
     * Get id
     *
     * @return id
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getId() {
        return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public UserDto type(Type type) {
    this.type = type;
    return this;
  }

    /**
     * Get type
     *
     * @return type
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Type getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(Type type) {
    this.type = type;
  }


  public UserDto name(String name) {
      this.name = name;
      return this;
  }

    /**
     * Get name
     *
     * @return name
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public UserDto pictureUrl(String pictureUrl) {
      this.pictureUrl = pictureUrl;
      return this;
  }

    /**
     * Get pictureUrl
     *
     * @return pictureUrl
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_PICTURE_URL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPictureUrl() {
    return pictureUrl;
  }


  @JsonProperty(JSON_PROPERTY_PICTURE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPictureUrl(String pictureUrl) {
    this.pictureUrl = pictureUrl;
  }


    public UserDto email(String email) {
        this.email = email;
        return this;
    }

    /**
     * Get email
     *
     * @return email
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_EMAIL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(String email) {
    this.email = email;
  }


  public UserDto devices(Set<DeviceDto> devices) {
      this.devices = devices;
      return this;
  }

    public UserDto addDevicesItem(DeviceDto devicesItem) {
    if (this.devices == null) {
        this.devices = new LinkedHashSet<>();
    }
        this.devices.add(devicesItem);
        return this;
    }

    /**
     * Get devices
     *
     * @return devices
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_DEVICES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<DeviceDto> getDevices() {
    return devices;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_DEVICES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDevices(Set<DeviceDto> devices) {
    this.devices = devices;
  }


    public UserDto ecdhPublicKey(String ecdhPublicKey) {
        this.ecdhPublicKey = ecdhPublicKey;
        return this;
    }

    /**
     * Get ecdhPublicKey
     *
     * @return ecdhPublicKey
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_ECDH_PUBLIC_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEcdhPublicKey() {
    return ecdhPublicKey;
  }


  @JsonProperty(JSON_PROPERTY_ECDH_PUBLIC_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEcdhPublicKey(String ecdhPublicKey) {
    this.ecdhPublicKey = ecdhPublicKey;
  }


    public UserDto ecdsaPublicKey(String ecdsaPublicKey) {
        this.ecdsaPublicKey = ecdsaPublicKey;
        return this;
    }

    /**
     * Get ecdsaPublicKey
     *
     * @return ecdsaPublicKey
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_ECDSA_PUBLIC_KEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEcdsaPublicKey() {
    return ecdsaPublicKey;
  }


  @JsonProperty(JSON_PROPERTY_ECDSA_PUBLIC_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEcdsaPublicKey(String ecdsaPublicKey) {
      this.ecdsaPublicKey = ecdsaPublicKey;
  }


    public UserDto privateKey(String privateKey) {
        this.privateKey = privateKey;
    return this;
  }

   /**
   * Get privateKey
   * @return privateKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PRIVATE_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPrivateKey() {
    return privateKey;
  }


  @JsonProperty(JSON_PROPERTY_PRIVATE_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrivateKey(String privateKey) {
    this.privateKey = privateKey;
  }


  public UserDto setupCode(String setupCode) {
    this.setupCode = setupCode;
    return this;
  }

   /**
   * Get setupCode
   * @return setupCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SETUP_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSetupCode() {
    return setupCode;
  }


  @JsonProperty(JSON_PROPERTY_SETUP_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSetupCode(String setupCode) {
      this.setupCode = setupCode;
  }


    public UserDto publicKey(String publicKey) {
        this.publicKey = publicKey;
        return this;
    }

    /**
     * Get publicKey
     *
     * @return publicKey
     * @deprecated
     **/
    @Deprecated
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    @JsonProperty(JSON_PROPERTY_PUBLIC_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPublicKey() {
    return publicKey;
  }


  @JsonProperty(JSON_PROPERTY_PUBLIC_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublicKey(String publicKey) {
      this.publicKey = publicKey;
  }


    /**
     * Return true if this UserDto object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        if(this == o) {
            return true;
        }
        if(o == null || getClass() != o.getClass()) {
            return false;
        }
        UserDto userDto = (UserDto) o;
        return Objects.equals(this.id, userDto.id) &&
                Objects.equals(this.type, userDto.type) &&
                Objects.equals(this.name, userDto.name) &&
                Objects.equals(this.pictureUrl, userDto.pictureUrl) &&
                Objects.equals(this.email, userDto.email) &&
                Objects.equals(this.devices, userDto.devices) &&
                Objects.equals(this.ecdhPublicKey, userDto.ecdhPublicKey) &&
                Objects.equals(this.ecdsaPublicKey, userDto.ecdsaPublicKey) &&
                Objects.equals(this.privateKey, userDto.privateKey) &&
        Objects.equals(this.setupCode, userDto.setupCode) &&
        Objects.equals(this.publicKey, userDto.publicKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, name, pictureUrl, email, devices, ecdhPublicKey, ecdsaPublicKey, privateKey, setupCode, publicKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pictureUrl: ").append(toIndentedString(pictureUrl)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    devices: ").append(toIndentedString(devices)).append("\n");
    sb.append("    ecdhPublicKey: ").append(toIndentedString(ecdhPublicKey)).append("\n");
    sb.append("    ecdsaPublicKey: ").append(toIndentedString(ecdsaPublicKey)).append("\n");
    sb.append("    privateKey: ").append(toIndentedString(privateKey)).append("\n");
    sb.append("    setupCode: ").append(toIndentedString(setupCode)).append("\n");
    sb.append("    publicKey: ").append(toIndentedString(publicKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

