/*
 * hub-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.katta.client.model;

import org.joda.time.DateTime;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * BillingDto
 */
@JsonPropertyOrder({
  BillingDto.JSON_PROPERTY_HUB_ID,
  BillingDto.JSON_PROPERTY_HAS_LICENSE,
  BillingDto.JSON_PROPERTY_EMAIL,
  BillingDto.JSON_PROPERTY_LICENSED_SEATS,
  BillingDto.JSON_PROPERTY_USED_SEATS,
  BillingDto.JSON_PROPERTY_ISSUED_AT,
  BillingDto.JSON_PROPERTY_EXPIRES_AT,
  BillingDto.JSON_PROPERTY_MANAGED_INSTANCE
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class BillingDto {
  public static final String JSON_PROPERTY_HUB_ID = "hubId";
  @javax.annotation.Nullable
  private String hubId;

  public static final String JSON_PROPERTY_HAS_LICENSE = "hasLicense";
  @javax.annotation.Nullable
  private Boolean hasLicense;

  public static final String JSON_PROPERTY_EMAIL = "email";
  @javax.annotation.Nullable
  private String email;

  public static final String JSON_PROPERTY_LICENSED_SEATS = "licensedSeats";
  @javax.annotation.Nullable
  private Integer licensedSeats;

  public static final String JSON_PROPERTY_USED_SEATS = "usedSeats";
  @javax.annotation.Nullable
  private Integer usedSeats;

  public static final String JSON_PROPERTY_ISSUED_AT = "issuedAt";
  @javax.annotation.Nullable
  private DateTime issuedAt;

  public static final String JSON_PROPERTY_EXPIRES_AT = "expiresAt";
  @javax.annotation.Nullable
  private DateTime expiresAt;

  public static final String JSON_PROPERTY_MANAGED_INSTANCE = "managedInstance";
  @javax.annotation.Nullable
  private Boolean managedInstance;

  public BillingDto() {
  }

  public BillingDto hubId(@javax.annotation.Nullable String hubId) {
    this.hubId = hubId;
    return this;
  }

  /**
   * Get hubId
   * @return hubId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HUB_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHubId() {
    return hubId;
  }


  @JsonProperty(JSON_PROPERTY_HUB_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHubId(@javax.annotation.Nullable String hubId) {
    this.hubId = hubId;
  }


  public BillingDto hasLicense(@javax.annotation.Nullable Boolean hasLicense) {
    this.hasLicense = hasLicense;
    return this;
  }

  /**
   * Get hasLicense
   * @return hasLicense
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HAS_LICENSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasLicense() {
    return hasLicense;
  }


  @JsonProperty(JSON_PROPERTY_HAS_LICENSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasLicense(@javax.annotation.Nullable Boolean hasLicense) {
    this.hasLicense = hasLicense;
  }


  public BillingDto email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * Get email
   * @return email
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public BillingDto licensedSeats(@javax.annotation.Nullable Integer licensedSeats) {
    this.licensedSeats = licensedSeats;
    return this;
  }

  /**
   * Get licensedSeats
   * @return licensedSeats
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LICENSED_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLicensedSeats() {
    return licensedSeats;
  }


  @JsonProperty(JSON_PROPERTY_LICENSED_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLicensedSeats(@javax.annotation.Nullable Integer licensedSeats) {
    this.licensedSeats = licensedSeats;
  }


  public BillingDto usedSeats(@javax.annotation.Nullable Integer usedSeats) {
    this.usedSeats = usedSeats;
    return this;
  }

  /**
   * Get usedSeats
   * @return usedSeats
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USED_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUsedSeats() {
    return usedSeats;
  }


  @JsonProperty(JSON_PROPERTY_USED_SEATS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsedSeats(@javax.annotation.Nullable Integer usedSeats) {
    this.usedSeats = usedSeats;
  }


  public BillingDto issuedAt(@javax.annotation.Nullable DateTime issuedAt) {
    this.issuedAt = issuedAt;
    return this;
  }

  /**
   * Get issuedAt
   * @return issuedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ISSUED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DateTime getIssuedAt() {
    return issuedAt;
  }


  @JsonProperty(JSON_PROPERTY_ISSUED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssuedAt(@javax.annotation.Nullable DateTime issuedAt) {
    this.issuedAt = issuedAt;
  }


  public BillingDto expiresAt(@javax.annotation.Nullable DateTime expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DateTime getExpiresAt() {
    return expiresAt;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiresAt(@javax.annotation.Nullable DateTime expiresAt) {
    this.expiresAt = expiresAt;
  }


  public BillingDto managedInstance(@javax.annotation.Nullable Boolean managedInstance) {
    this.managedInstance = managedInstance;
    return this;
  }

  /**
   * Get managedInstance
   * @return managedInstance
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGED_INSTANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getManagedInstance() {
    return managedInstance;
  }


  @JsonProperty(JSON_PROPERTY_MANAGED_INSTANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManagedInstance(@javax.annotation.Nullable Boolean managedInstance) {
    this.managedInstance = managedInstance;
  }


  /**
   * Return true if this BillingDto object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillingDto billingDto = (BillingDto) o;
    return Objects.equals(this.hubId, billingDto.hubId) &&
        Objects.equals(this.hasLicense, billingDto.hasLicense) &&
        Objects.equals(this.email, billingDto.email) &&
        Objects.equals(this.licensedSeats, billingDto.licensedSeats) &&
        Objects.equals(this.usedSeats, billingDto.usedSeats) &&
        Objects.equals(this.issuedAt, billingDto.issuedAt) &&
        Objects.equals(this.expiresAt, billingDto.expiresAt) &&
        Objects.equals(this.managedInstance, billingDto.managedInstance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hubId, hasLicense, email, licensedSeats, usedSeats, issuedAt, expiresAt, managedInstance);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillingDto {\n");
    sb.append("    hubId: ").append(toIndentedString(hubId)).append("\n");
    sb.append("    hasLicense: ").append(toIndentedString(hasLicense)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    licensedSeats: ").append(toIndentedString(licensedSeats)).append("\n");
    sb.append("    usedSeats: ").append(toIndentedString(usedSeats)).append("\n");
    sb.append("    issuedAt: ").append(toIndentedString(issuedAt)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    managedInstance: ").append(toIndentedString(managedInstance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

