/*
 * hub-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.katta.client.model;

import org.joda.time.DateTime;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * ConfigDto
 */
@JsonPropertyOrder({
  ConfigDto.JSON_PROPERTY_KEYCLOAK_URL,
  ConfigDto.JSON_PROPERTY_KEYCLOAK_REALM,
  ConfigDto.JSON_PROPERTY_KEYCLOAK_CLIENT_ID_HUB,
  ConfigDto.JSON_PROPERTY_KEYCLOAK_CLIENT_ID_CRYPTOMATOR,
  ConfigDto.JSON_PROPERTY_KEYCLOAK_AUTH_ENDPOINT,
  ConfigDto.JSON_PROPERTY_KEYCLOAK_TOKEN_ENDPOINT,
  ConfigDto.JSON_PROPERTY_SERVER_TIME,
  ConfigDto.JSON_PROPERTY_API_LEVEL,
  ConfigDto.JSON_PROPERTY_KEYCLOAK_CLIENT_ID_CRYPTOMATOR_VAULTS,
  ConfigDto.JSON_PROPERTY_UUID
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class ConfigDto {
  public static final String JSON_PROPERTY_KEYCLOAK_URL = "keycloakUrl";
  @javax.annotation.Nullable
  private String keycloakUrl;

  public static final String JSON_PROPERTY_KEYCLOAK_REALM = "keycloakRealm";
  @javax.annotation.Nullable
  private String keycloakRealm;

  public static final String JSON_PROPERTY_KEYCLOAK_CLIENT_ID_HUB = "keycloakClientIdHub";
  @javax.annotation.Nullable
  private String keycloakClientIdHub;

  public static final String JSON_PROPERTY_KEYCLOAK_CLIENT_ID_CRYPTOMATOR = "keycloakClientIdCryptomator";
  @javax.annotation.Nullable
  private String keycloakClientIdCryptomator;

  public static final String JSON_PROPERTY_KEYCLOAK_AUTH_ENDPOINT = "keycloakAuthEndpoint";
  @javax.annotation.Nullable
  private String keycloakAuthEndpoint;

  public static final String JSON_PROPERTY_KEYCLOAK_TOKEN_ENDPOINT = "keycloakTokenEndpoint";
  @javax.annotation.Nullable
  private String keycloakTokenEndpoint;

  public static final String JSON_PROPERTY_SERVER_TIME = "serverTime";
  @javax.annotation.Nullable
  private DateTime serverTime;

  public static final String JSON_PROPERTY_API_LEVEL = "apiLevel";
  @javax.annotation.Nullable
  private Integer apiLevel;

  public static final String JSON_PROPERTY_KEYCLOAK_CLIENT_ID_CRYPTOMATOR_VAULTS = "keycloakClientIdCryptomatorVaults";
  @javax.annotation.Nullable
  private String keycloakClientIdCryptomatorVaults;

  public static final String JSON_PROPERTY_UUID = "uuid";
  @javax.annotation.Nullable
  private String uuid;

  public ConfigDto() {
  }

  public ConfigDto keycloakUrl(@javax.annotation.Nullable String keycloakUrl) {
    this.keycloakUrl = keycloakUrl;
    return this;
  }

  /**
   * Get keycloakUrl
   * @return keycloakUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEYCLOAK_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKeycloakUrl() {
    return keycloakUrl;
  }


  @JsonProperty(JSON_PROPERTY_KEYCLOAK_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeycloakUrl(@javax.annotation.Nullable String keycloakUrl) {
    this.keycloakUrl = keycloakUrl;
  }


  public ConfigDto keycloakRealm(@javax.annotation.Nullable String keycloakRealm) {
    this.keycloakRealm = keycloakRealm;
    return this;
  }

  /**
   * Get keycloakRealm
   * @return keycloakRealm
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEYCLOAK_REALM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKeycloakRealm() {
    return keycloakRealm;
  }


  @JsonProperty(JSON_PROPERTY_KEYCLOAK_REALM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeycloakRealm(@javax.annotation.Nullable String keycloakRealm) {
    this.keycloakRealm = keycloakRealm;
  }


  public ConfigDto keycloakClientIdHub(@javax.annotation.Nullable String keycloakClientIdHub) {
    this.keycloakClientIdHub = keycloakClientIdHub;
    return this;
  }

  /**
   * Get keycloakClientIdHub
   * @return keycloakClientIdHub
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEYCLOAK_CLIENT_ID_HUB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKeycloakClientIdHub() {
    return keycloakClientIdHub;
  }


  @JsonProperty(JSON_PROPERTY_KEYCLOAK_CLIENT_ID_HUB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeycloakClientIdHub(@javax.annotation.Nullable String keycloakClientIdHub) {
    this.keycloakClientIdHub = keycloakClientIdHub;
  }


  public ConfigDto keycloakClientIdCryptomator(@javax.annotation.Nullable String keycloakClientIdCryptomator) {
    this.keycloakClientIdCryptomator = keycloakClientIdCryptomator;
    return this;
  }

  /**
   * Get keycloakClientIdCryptomator
   * @return keycloakClientIdCryptomator
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEYCLOAK_CLIENT_ID_CRYPTOMATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKeycloakClientIdCryptomator() {
    return keycloakClientIdCryptomator;
  }


  @JsonProperty(JSON_PROPERTY_KEYCLOAK_CLIENT_ID_CRYPTOMATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeycloakClientIdCryptomator(@javax.annotation.Nullable String keycloakClientIdCryptomator) {
    this.keycloakClientIdCryptomator = keycloakClientIdCryptomator;
  }


  public ConfigDto keycloakAuthEndpoint(@javax.annotation.Nullable String keycloakAuthEndpoint) {
    this.keycloakAuthEndpoint = keycloakAuthEndpoint;
    return this;
  }

  /**
   * Get keycloakAuthEndpoint
   * @return keycloakAuthEndpoint
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEYCLOAK_AUTH_ENDPOINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKeycloakAuthEndpoint() {
    return keycloakAuthEndpoint;
  }


  @JsonProperty(JSON_PROPERTY_KEYCLOAK_AUTH_ENDPOINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeycloakAuthEndpoint(@javax.annotation.Nullable String keycloakAuthEndpoint) {
    this.keycloakAuthEndpoint = keycloakAuthEndpoint;
  }


  public ConfigDto keycloakTokenEndpoint(@javax.annotation.Nullable String keycloakTokenEndpoint) {
    this.keycloakTokenEndpoint = keycloakTokenEndpoint;
    return this;
  }

  /**
   * Get keycloakTokenEndpoint
   * @return keycloakTokenEndpoint
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEYCLOAK_TOKEN_ENDPOINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKeycloakTokenEndpoint() {
    return keycloakTokenEndpoint;
  }


  @JsonProperty(JSON_PROPERTY_KEYCLOAK_TOKEN_ENDPOINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeycloakTokenEndpoint(@javax.annotation.Nullable String keycloakTokenEndpoint) {
    this.keycloakTokenEndpoint = keycloakTokenEndpoint;
  }


  public ConfigDto serverTime(@javax.annotation.Nullable DateTime serverTime) {
    this.serverTime = serverTime;
    return this;
  }

  /**
   * Get serverTime
   * @return serverTime
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERVER_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DateTime getServerTime() {
    return serverTime;
  }


  @JsonProperty(JSON_PROPERTY_SERVER_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServerTime(@javax.annotation.Nullable DateTime serverTime) {
    this.serverTime = serverTime;
  }


  public ConfigDto apiLevel(@javax.annotation.Nullable Integer apiLevel) {
    this.apiLevel = apiLevel;
    return this;
  }

  /**
   * Get apiLevel
   * @return apiLevel
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_API_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getApiLevel() {
    return apiLevel;
  }


  @JsonProperty(JSON_PROPERTY_API_LEVEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApiLevel(@javax.annotation.Nullable Integer apiLevel) {
    this.apiLevel = apiLevel;
  }


  public ConfigDto keycloakClientIdCryptomatorVaults(@javax.annotation.Nullable String keycloakClientIdCryptomatorVaults) {
    this.keycloakClientIdCryptomatorVaults = keycloakClientIdCryptomatorVaults;
    return this;
  }

  /**
   * Get keycloakClientIdCryptomatorVaults
   * @return keycloakClientIdCryptomatorVaults
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEYCLOAK_CLIENT_ID_CRYPTOMATOR_VAULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKeycloakClientIdCryptomatorVaults() {
    return keycloakClientIdCryptomatorVaults;
  }


  @JsonProperty(JSON_PROPERTY_KEYCLOAK_CLIENT_ID_CRYPTOMATOR_VAULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeycloakClientIdCryptomatorVaults(@javax.annotation.Nullable String keycloakClientIdCryptomatorVaults) {
    this.keycloakClientIdCryptomatorVaults = keycloakClientIdCryptomatorVaults;
  }


  public ConfigDto uuid(@javax.annotation.Nullable String uuid) {
    this.uuid = uuid;
    return this;
  }

  /**
   * Get uuid
   * @return uuid
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUuid() {
    return uuid;
  }


  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUuid(@javax.annotation.Nullable String uuid) {
    this.uuid = uuid;
  }


  /**
   * Return true if this ConfigDto object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfigDto configDto = (ConfigDto) o;
    return Objects.equals(this.keycloakUrl, configDto.keycloakUrl) &&
        Objects.equals(this.keycloakRealm, configDto.keycloakRealm) &&
        Objects.equals(this.keycloakClientIdHub, configDto.keycloakClientIdHub) &&
        Objects.equals(this.keycloakClientIdCryptomator, configDto.keycloakClientIdCryptomator) &&
        Objects.equals(this.keycloakAuthEndpoint, configDto.keycloakAuthEndpoint) &&
        Objects.equals(this.keycloakTokenEndpoint, configDto.keycloakTokenEndpoint) &&
        Objects.equals(this.serverTime, configDto.serverTime) &&
        Objects.equals(this.apiLevel, configDto.apiLevel) &&
        Objects.equals(this.keycloakClientIdCryptomatorVaults, configDto.keycloakClientIdCryptomatorVaults) &&
        Objects.equals(this.uuid, configDto.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keycloakUrl, keycloakRealm, keycloakClientIdHub, keycloakClientIdCryptomator, keycloakAuthEndpoint, keycloakTokenEndpoint, serverTime, apiLevel, keycloakClientIdCryptomatorVaults, uuid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfigDto {\n");
    sb.append("    keycloakUrl: ").append(toIndentedString(keycloakUrl)).append("\n");
    sb.append("    keycloakRealm: ").append(toIndentedString(keycloakRealm)).append("\n");
    sb.append("    keycloakClientIdHub: ").append(toIndentedString(keycloakClientIdHub)).append("\n");
    sb.append("    keycloakClientIdCryptomator: ").append(toIndentedString(keycloakClientIdCryptomator)).append("\n");
    sb.append("    keycloakAuthEndpoint: ").append(toIndentedString(keycloakAuthEndpoint)).append("\n");
    sb.append("    keycloakTokenEndpoint: ").append(toIndentedString(keycloakTokenEndpoint)).append("\n");
    sb.append("    serverTime: ").append(toIndentedString(serverTime)).append("\n");
    sb.append("    apiLevel: ").append(toIndentedString(apiLevel)).append("\n");
    sb.append("    keycloakClientIdCryptomatorVaults: ").append(toIndentedString(keycloakClientIdCryptomatorVaults)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

