/*
 * hub-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.katta.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import cloud.katta.client.model.Type1;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import cloud.katta.client.JSON;


/**
 * DeviceDto
 */
@JsonPropertyOrder({
  DeviceDto.JSON_PROPERTY_ID,
  DeviceDto.JSON_PROPERTY_NAME,
  DeviceDto.JSON_PROPERTY_TYPE,
  DeviceDto.JSON_PROPERTY_PUBLIC_KEY,
  DeviceDto.JSON_PROPERTY_USER_PRIVATE_KEY,
  DeviceDto.JSON_PROPERTY_OWNER,
  DeviceDto.JSON_PROPERTY_CREATION_TIME,
  DeviceDto.JSON_PROPERTY_LAST_IP_ADDRESS,
  DeviceDto.JSON_PROPERTY_LAST_ACCESS_TIME,
  DeviceDto.JSON_PROPERTY_LEGACY_DEVICE
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class DeviceDto {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nullable
  private Type1 type;

  public static final String JSON_PROPERTY_PUBLIC_KEY = "publicKey";
  @javax.annotation.Nonnull
  private String publicKey;

  public static final String JSON_PROPERTY_USER_PRIVATE_KEY = "userPrivateKey";
  @javax.annotation.Nonnull
  private String userPrivateKey;

  public static final String JSON_PROPERTY_OWNER = "owner";
  @javax.annotation.Nullable
  private String owner;

  public static final String JSON_PROPERTY_CREATION_TIME = "creationTime";
  @javax.annotation.Nullable
  private DateTime creationTime;

  public static final String JSON_PROPERTY_LAST_IP_ADDRESS = "lastIpAddress";
  @javax.annotation.Nullable
  private String lastIpAddress;

  public static final String JSON_PROPERTY_LAST_ACCESS_TIME = "lastAccessTime";
  @javax.annotation.Nullable
  private DateTime lastAccessTime;

  public static final String JSON_PROPERTY_LEGACY_DEVICE = "legacyDevice";
  @javax.annotation.Nullable
  private Boolean legacyDevice;

  public DeviceDto() { 
  }

  public DeviceDto id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public DeviceDto name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public DeviceDto type(@javax.annotation.Nullable Type1 type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Type1 getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@javax.annotation.Nullable Type1 type) {
    this.type = type;
  }


  public DeviceDto publicKey(@javax.annotation.Nonnull String publicKey) {
    this.publicKey = publicKey;
    return this;
  }

  /**
   * Get publicKey
   * @return publicKey
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PUBLIC_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPublicKey() {
    return publicKey;
  }


  @JsonProperty(JSON_PROPERTY_PUBLIC_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPublicKey(@javax.annotation.Nonnull String publicKey) {
    this.publicKey = publicKey;
  }


  public DeviceDto userPrivateKey(@javax.annotation.Nonnull String userPrivateKey) {
    this.userPrivateKey = userPrivateKey;
    return this;
  }

  /**
   * Get userPrivateKey
   * @return userPrivateKey
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_USER_PRIVATE_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUserPrivateKey() {
    return userPrivateKey;
  }


  @JsonProperty(JSON_PROPERTY_USER_PRIVATE_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserPrivateKey(@javax.annotation.Nonnull String userPrivateKey) {
    this.userPrivateKey = userPrivateKey;
  }


  public DeviceDto owner(@javax.annotation.Nullable String owner) {
    this.owner = owner;
    return this;
  }

  /**
   * Get owner
   * @return owner
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OWNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOwner() {
    return owner;
  }


  @JsonProperty(JSON_PROPERTY_OWNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwner(@javax.annotation.Nullable String owner) {
    this.owner = owner;
  }


  public DeviceDto creationTime(@javax.annotation.Nullable DateTime creationTime) {
    this.creationTime = creationTime;
    return this;
  }

  /**
   * Get creationTime
   * @return creationTime
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATION_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DateTime getCreationTime() {
    return creationTime;
  }


  @JsonProperty(JSON_PROPERTY_CREATION_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreationTime(@javax.annotation.Nullable DateTime creationTime) {
    this.creationTime = creationTime;
  }


  public DeviceDto lastIpAddress(@javax.annotation.Nullable String lastIpAddress) {
    this.lastIpAddress = lastIpAddress;
    return this;
  }

  /**
   * Get lastIpAddress
   * @return lastIpAddress
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_IP_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastIpAddress() {
    return lastIpAddress;
  }


  @JsonProperty(JSON_PROPERTY_LAST_IP_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastIpAddress(@javax.annotation.Nullable String lastIpAddress) {
    this.lastIpAddress = lastIpAddress;
  }


  public DeviceDto lastAccessTime(@javax.annotation.Nullable DateTime lastAccessTime) {
    this.lastAccessTime = lastAccessTime;
    return this;
  }

  /**
   * Get lastAccessTime
   * @return lastAccessTime
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_ACCESS_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DateTime getLastAccessTime() {
    return lastAccessTime;
  }


  @JsonProperty(JSON_PROPERTY_LAST_ACCESS_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastAccessTime(@javax.annotation.Nullable DateTime lastAccessTime) {
    this.lastAccessTime = lastAccessTime;
  }


  public DeviceDto legacyDevice(@javax.annotation.Nullable Boolean legacyDevice) {
    this.legacyDevice = legacyDevice;
    return this;
  }

  /**
   * Get legacyDevice
   * @return legacyDevice
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEGACY_DEVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLegacyDevice() {
    return legacyDevice;
  }


  @JsonProperty(JSON_PROPERTY_LEGACY_DEVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLegacyDevice(@javax.annotation.Nullable Boolean legacyDevice) {
    this.legacyDevice = legacyDevice;
  }


  /**
   * Return true if this DeviceDto object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceDto deviceDto = (DeviceDto) o;
    return Objects.equals(this.id, deviceDto.id) &&
        Objects.equals(this.name, deviceDto.name) &&
        Objects.equals(this.type, deviceDto.type) &&
        Objects.equals(this.publicKey, deviceDto.publicKey) &&
        Objects.equals(this.userPrivateKey, deviceDto.userPrivateKey) &&
        Objects.equals(this.owner, deviceDto.owner) &&
        Objects.equals(this.creationTime, deviceDto.creationTime) &&
        Objects.equals(this.lastIpAddress, deviceDto.lastIpAddress) &&
        Objects.equals(this.lastAccessTime, deviceDto.lastAccessTime) &&
        Objects.equals(this.legacyDevice, deviceDto.legacyDevice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, type, publicKey, userPrivateKey, owner, creationTime, lastIpAddress, lastAccessTime, legacyDevice);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    publicKey: ").append(toIndentedString(publicKey)).append("\n");
    sb.append("    userPrivateKey: ").append(toIndentedString(userPrivateKey)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    lastIpAddress: ").append(toIndentedString(lastIpAddress)).append("\n");
    sb.append("    lastAccessTime: ").append(toIndentedString(lastAccessTime)).append("\n");
    sb.append("    legacyDevice: ").append(toIndentedString(legacyDevice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

