/*
 * hub-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.katta.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import cloud.katta.client.model.Role;
import cloud.katta.client.model.Type;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import cloud.katta.client.JSON;


/**
 * MemberDto
 */
@JsonPropertyOrder({
  MemberDto.JSON_PROPERTY_ID,
  MemberDto.JSON_PROPERTY_TYPE,
  MemberDto.JSON_PROPERTY_NAME,
  MemberDto.JSON_PROPERTY_PICTURE_URL,
  MemberDto.JSON_PROPERTY_ECDH_PUBLIC_KEY,
  MemberDto.JSON_PROPERTY_ECDSA_PUBLIC_KEY,
  MemberDto.JSON_PROPERTY_ROLE,
  MemberDto.JSON_PROPERTY_MEMBER_SIZE
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class MemberDto {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nullable
  private Type type;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_PICTURE_URL = "pictureUrl";
  @javax.annotation.Nullable
  private String pictureUrl;

  public static final String JSON_PROPERTY_ECDH_PUBLIC_KEY = "ecdhPublicKey";
  @javax.annotation.Nullable
  private String ecdhPublicKey;

  public static final String JSON_PROPERTY_ECDSA_PUBLIC_KEY = "ecdsaPublicKey";
  @javax.annotation.Nullable
  private String ecdsaPublicKey;

  public static final String JSON_PROPERTY_ROLE = "role";
  @javax.annotation.Nullable
  private Role role;

  public static final String JSON_PROPERTY_MEMBER_SIZE = "memberSize";
  @javax.annotation.Nullable
  private Integer memberSize;

  public MemberDto() { 
  }

  public MemberDto id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public MemberDto type(@javax.annotation.Nullable Type type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Type getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@javax.annotation.Nullable Type type) {
    this.type = type;
  }


  public MemberDto name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public MemberDto pictureUrl(@javax.annotation.Nullable String pictureUrl) {
    this.pictureUrl = pictureUrl;
    return this;
  }

  /**
   * Get pictureUrl
   * @return pictureUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PICTURE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPictureUrl() {
    return pictureUrl;
  }


  @JsonProperty(JSON_PROPERTY_PICTURE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPictureUrl(@javax.annotation.Nullable String pictureUrl) {
    this.pictureUrl = pictureUrl;
  }


  public MemberDto ecdhPublicKey(@javax.annotation.Nullable String ecdhPublicKey) {
    this.ecdhPublicKey = ecdhPublicKey;
    return this;
  }

  /**
   * Get ecdhPublicKey
   * @return ecdhPublicKey
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ECDH_PUBLIC_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEcdhPublicKey() {
    return ecdhPublicKey;
  }


  @JsonProperty(JSON_PROPERTY_ECDH_PUBLIC_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEcdhPublicKey(@javax.annotation.Nullable String ecdhPublicKey) {
    this.ecdhPublicKey = ecdhPublicKey;
  }


  public MemberDto ecdsaPublicKey(@javax.annotation.Nullable String ecdsaPublicKey) {
    this.ecdsaPublicKey = ecdsaPublicKey;
    return this;
  }

  /**
   * Get ecdsaPublicKey
   * @return ecdsaPublicKey
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ECDSA_PUBLIC_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEcdsaPublicKey() {
    return ecdsaPublicKey;
  }


  @JsonProperty(JSON_PROPERTY_ECDSA_PUBLIC_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEcdsaPublicKey(@javax.annotation.Nullable String ecdsaPublicKey) {
    this.ecdsaPublicKey = ecdsaPublicKey;
  }


  public MemberDto role(@javax.annotation.Nullable Role role) {
    this.role = role;
    return this;
  }

  /**
   * Get role
   * @return role
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Role getRole() {
    return role;
  }


  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRole(@javax.annotation.Nullable Role role) {
    this.role = role;
  }


  public MemberDto memberSize(@javax.annotation.Nullable Integer memberSize) {
    this.memberSize = memberSize;
    return this;
  }

  /**
   * Get memberSize
   * @return memberSize
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MEMBER_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMemberSize() {
    return memberSize;
  }


  @JsonProperty(JSON_PROPERTY_MEMBER_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMemberSize(@javax.annotation.Nullable Integer memberSize) {
    this.memberSize = memberSize;
  }


  /**
   * Return true if this MemberDto object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MemberDto memberDto = (MemberDto) o;
    return Objects.equals(this.id, memberDto.id) &&
        Objects.equals(this.type, memberDto.type) &&
        Objects.equals(this.name, memberDto.name) &&
        Objects.equals(this.pictureUrl, memberDto.pictureUrl) &&
        Objects.equals(this.ecdhPublicKey, memberDto.ecdhPublicKey) &&
        Objects.equals(this.ecdsaPublicKey, memberDto.ecdsaPublicKey) &&
        Objects.equals(this.role, memberDto.role) &&
        Objects.equals(this.memberSize, memberDto.memberSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, name, pictureUrl, ecdhPublicKey, ecdsaPublicKey, role, memberSize);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MemberDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pictureUrl: ").append(toIndentedString(pictureUrl)).append("\n");
    sb.append("    ecdhPublicKey: ").append(toIndentedString(ecdhPublicKey)).append("\n");
    sb.append("    ecdsaPublicKey: ").append(toIndentedString(ecdsaPublicKey)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    memberSize: ").append(toIndentedString(memberSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

