/*
 * Copyright (c) 2025 shift7 GmbH. All rights reserved.
 */

/*
 * hub-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.katta.client.model;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets S3_SERVERSIDE_ENCRYPTION
 */
public enum S3SERVERSIDEENCRYPTION {

  NONE("NONE"),

  SSE_AES256("SSE_AES256"),

  SSE_KMS_DEFAULT("SSE_KMS_DEFAULT");

  private String value;

  S3SERVERSIDEENCRYPTION(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static S3SERVERSIDEENCRYPTION fromValue(String value) {
    for (S3SERVERSIDEENCRYPTION b : S3SERVERSIDEENCRYPTION.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

