/*
 * Copyright (c) 2025 shift7 GmbH. All rights reserved.
 */

/*
 * hub-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.katta.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.UUID;
import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * VaultDto
 */
@JsonPropertyOrder({
  VaultDto.JSON_PROPERTY_ID,
  VaultDto.JSON_PROPERTY_NAME,
  VaultDto.JSON_PROPERTY_DESCRIPTION,
  VaultDto.JSON_PROPERTY_ARCHIVED,
  VaultDto.JSON_PROPERTY_CREATION_TIME,
  VaultDto.JSON_PROPERTY_UVF_METADATA_FILE,
  VaultDto.JSON_PROPERTY_UVF_KEY_SET,
  VaultDto.JSON_PROPERTY_MASTERKEY,
  VaultDto.JSON_PROPERTY_ITERATIONS,
  VaultDto.JSON_PROPERTY_SALT,
  VaultDto.JSON_PROPERTY_AUTH_PUBLIC_KEY,
  VaultDto.JSON_PROPERTY_AUTH_PRIVATE_KEY
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class VaultDto {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_ARCHIVED = "archived";
  @javax.annotation.Nullable
  private Boolean archived;

  public static final String JSON_PROPERTY_CREATION_TIME = "creationTime";
  @javax.annotation.Nullable
  private DateTime creationTime;

  public static final String JSON_PROPERTY_UVF_METADATA_FILE = "uvfMetadataFile";
  @javax.annotation.Nullable
  private String uvfMetadataFile;

  public static final String JSON_PROPERTY_UVF_KEY_SET = "uvfKeySet";
  @javax.annotation.Nullable
  private String uvfKeySet;

  public static final String JSON_PROPERTY_MASTERKEY = "masterkey";
  @javax.annotation.Nullable
  private String masterkey;

  public static final String JSON_PROPERTY_ITERATIONS = "iterations";
  @javax.annotation.Nullable
  private Integer iterations;

  public static final String JSON_PROPERTY_SALT = "salt";
  @javax.annotation.Nullable
  private String salt;

  public static final String JSON_PROPERTY_AUTH_PUBLIC_KEY = "authPublicKey";
  @javax.annotation.Nullable
  private String authPublicKey;

  public static final String JSON_PROPERTY_AUTH_PRIVATE_KEY = "authPrivateKey";
  @javax.annotation.Nullable
  private String authPrivateKey;

  public VaultDto() {
  }

  public VaultDto id(@javax.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public VaultDto name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public VaultDto description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public VaultDto archived(@javax.annotation.Nullable Boolean archived) {
    this.archived = archived;
    return this;
  }

  /**
   * Get archived
   * @return archived
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ARCHIVED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getArchived() {
    return archived;
  }


  @JsonProperty(JSON_PROPERTY_ARCHIVED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArchived(@javax.annotation.Nullable Boolean archived) {
    this.archived = archived;
  }


  public VaultDto creationTime(@javax.annotation.Nullable DateTime creationTime) {
    this.creationTime = creationTime;
    return this;
  }

  /**
   * Get creationTime
   * @return creationTime
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATION_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DateTime getCreationTime() {
    return creationTime;
  }


  @JsonProperty(JSON_PROPERTY_CREATION_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreationTime(@javax.annotation.Nullable DateTime creationTime) {
    this.creationTime = creationTime;
  }


  public VaultDto uvfMetadataFile(@javax.annotation.Nullable String uvfMetadataFile) {
    this.uvfMetadataFile = uvfMetadataFile;
    return this;
  }

  /**
   * Get uvfMetadataFile
   * @return uvfMetadataFile
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UVF_METADATA_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUvfMetadataFile() {
    return uvfMetadataFile;
  }


  @JsonProperty(JSON_PROPERTY_UVF_METADATA_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUvfMetadataFile(@javax.annotation.Nullable String uvfMetadataFile) {
    this.uvfMetadataFile = uvfMetadataFile;
  }


  public VaultDto uvfKeySet(@javax.annotation.Nullable String uvfKeySet) {
    this.uvfKeySet = uvfKeySet;
    return this;
  }

  /**
   * Get uvfKeySet
   * @return uvfKeySet
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UVF_KEY_SET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUvfKeySet() {
    return uvfKeySet;
  }


  @JsonProperty(JSON_PROPERTY_UVF_KEY_SET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUvfKeySet(@javax.annotation.Nullable String uvfKeySet) {
    this.uvfKeySet = uvfKeySet;
  }


  public VaultDto masterkey(@javax.annotation.Nullable String masterkey) {
    this.masterkey = masterkey;
    return this;
  }

  /**
   * Get masterkey
   * @return masterkey
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MASTERKEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMasterkey() {
    return masterkey;
  }


  @JsonProperty(JSON_PROPERTY_MASTERKEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMasterkey(@javax.annotation.Nullable String masterkey) {
    this.masterkey = masterkey;
  }


  public VaultDto iterations(@javax.annotation.Nullable Integer iterations) {
    this.iterations = iterations;
    return this;
  }

  /**
   * Get iterations
   * @return iterations
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ITERATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getIterations() {
    return iterations;
  }


  @JsonProperty(JSON_PROPERTY_ITERATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIterations(@javax.annotation.Nullable Integer iterations) {
    this.iterations = iterations;
  }


  public VaultDto salt(@javax.annotation.Nullable String salt) {
    this.salt = salt;
    return this;
  }

  /**
   * Get salt
   * @return salt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SALT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSalt() {
    return salt;
  }


  @JsonProperty(JSON_PROPERTY_SALT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSalt(@javax.annotation.Nullable String salt) {
    this.salt = salt;
  }


  public VaultDto authPublicKey(@javax.annotation.Nullable String authPublicKey) {
    this.authPublicKey = authPublicKey;
    return this;
  }

  /**
   * Get authPublicKey
   * @return authPublicKey
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTH_PUBLIC_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAuthPublicKey() {
    return authPublicKey;
  }


  @JsonProperty(JSON_PROPERTY_AUTH_PUBLIC_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthPublicKey(@javax.annotation.Nullable String authPublicKey) {
    this.authPublicKey = authPublicKey;
  }


  public VaultDto authPrivateKey(@javax.annotation.Nullable String authPrivateKey) {
    this.authPrivateKey = authPrivateKey;
    return this;
  }

  /**
   * Get authPrivateKey
   * @return authPrivateKey
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUTH_PRIVATE_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAuthPrivateKey() {
    return authPrivateKey;
  }


  @JsonProperty(JSON_PROPERTY_AUTH_PRIVATE_KEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthPrivateKey(@javax.annotation.Nullable String authPrivateKey) {
    this.authPrivateKey = authPrivateKey;
  }


  /**
   * Return true if this VaultDto object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VaultDto vaultDto = (VaultDto) o;
    return Objects.equals(this.id, vaultDto.id) &&
        Objects.equals(this.name, vaultDto.name) &&
        Objects.equals(this.description, vaultDto.description) &&
        Objects.equals(this.archived, vaultDto.archived) &&
        Objects.equals(this.creationTime, vaultDto.creationTime) &&
        Objects.equals(this.uvfMetadataFile, vaultDto.uvfMetadataFile) &&
        Objects.equals(this.uvfKeySet, vaultDto.uvfKeySet) &&
        Objects.equals(this.masterkey, vaultDto.masterkey) &&
        Objects.equals(this.iterations, vaultDto.iterations) &&
        Objects.equals(this.salt, vaultDto.salt) &&
        Objects.equals(this.authPublicKey, vaultDto.authPublicKey) &&
        Objects.equals(this.authPrivateKey, vaultDto.authPrivateKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, archived, creationTime, uvfMetadataFile, uvfKeySet, masterkey, iterations, salt, authPublicKey, authPrivateKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VaultDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    uvfMetadataFile: ").append(toIndentedString(uvfMetadataFile)).append("\n");
    sb.append("    uvfKeySet: ").append(toIndentedString(uvfKeySet)).append("\n");
    sb.append("    masterkey: ").append(toIndentedString(masterkey)).append("\n");
    sb.append("    iterations: ").append(toIndentedString(iterations)).append("\n");
    sb.append("    salt: ").append(toIndentedString(salt)).append("\n");
    sb.append("    authPublicKey: ").append(toIndentedString(authPublicKey)).append("\n");
    sb.append("    authPrivateKey: ").append(toIndentedString(authPrivateKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

