/*
 * hub-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.katta.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import cloud.katta.client.JSON;


/**
 * VersionDto
 */
@JsonPropertyOrder({
  VersionDto.JSON_PROPERTY_HUB_VERSION,
  VersionDto.JSON_PROPERTY_KEYCLOAK_VERSION
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class VersionDto {
  public static final String JSON_PROPERTY_HUB_VERSION = "hubVersion";
  @javax.annotation.Nullable
  private String hubVersion;

  public static final String JSON_PROPERTY_KEYCLOAK_VERSION = "keycloakVersion";
  @javax.annotation.Nullable
  private String keycloakVersion;

  public VersionDto() { 
  }

  public VersionDto hubVersion(@javax.annotation.Nullable String hubVersion) {
    this.hubVersion = hubVersion;
    return this;
  }

  /**
   * Get hubVersion
   * @return hubVersion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HUB_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHubVersion() {
    return hubVersion;
  }


  @JsonProperty(JSON_PROPERTY_HUB_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHubVersion(@javax.annotation.Nullable String hubVersion) {
    this.hubVersion = hubVersion;
  }


  public VersionDto keycloakVersion(@javax.annotation.Nullable String keycloakVersion) {
    this.keycloakVersion = keycloakVersion;
    return this;
  }

  /**
   * Get keycloakVersion
   * @return keycloakVersion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEYCLOAK_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKeycloakVersion() {
    return keycloakVersion;
  }


  @JsonProperty(JSON_PROPERTY_KEYCLOAK_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeycloakVersion(@javax.annotation.Nullable String keycloakVersion) {
    this.keycloakVersion = keycloakVersion;
  }


  /**
   * Return true if this VersionDto object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VersionDto versionDto = (VersionDto) o;
    return Objects.equals(this.hubVersion, versionDto.hubVersion) &&
        Objects.equals(this.keycloakVersion, versionDto.keycloakVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hubVersion, keycloakVersion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VersionDto {\n");
    sb.append("    hubVersion: ").append(toIndentedString(hubVersion)).append("\n");
    sb.append("    keycloakVersion: ").append(toIndentedString(keycloakVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

