name: Publish Snapshot Artifacts
on:
  push:
    branches:
      - main
jobs:
  snapshot:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Docker network prune
        run: docker network prune --force
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode deploy -DskipTests -DskipITs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
